---
title: "Portfolio 10: HMM Stage 1 - Proof-of-Concept 2-State Joint Hidden Markov Model"
---

# Background
Standard analyses of learned distractor suppression in the attentional-singleton paradigm compute block-level suppression scores (VD - CD) on RT or fixation probability. These scores collapes all trial-by-trial and fixation-level dynamics into a single number per block. A hidden Markov model (HMM) offers a complementary approach: it treats each trial's fixation sequence as generated by one of several latent attentional states, then tracks how the prevalence of those states shifts across trials and blocks as learning processes.

The gaze-contingent design in the Visual Search Task is critical for specifying the model structure. Because participants cannot distinguish target-colored distractors (TCDs) from the target prior to fixation, the hidden states must capture general processing modes, such as efficient target-directed search vs. distractor engagement, that are the same across CD and VD conditions. The suppression signal then manifests as a condition difference in state prevalence. As participants learn to suppress the consistent distractor (CD), the efficient search state should become more prevalent in CD relative to VD. THis VD-CD difference in state occupancy is the HMM analog of the standard behavioral suppression score.

The goal of this analysis is to fit a hidden Markov model (HMM) to the VST fixation data and evaluate whether it can recover learned distractor suppression as a latent process. Specifically, we aim to:

- Establish that a 2-state HMM recovers two interpretable attentional modes - efficient target-directed search vs. distractor engagement — from within-trial fixation sequences.
- Validate the model by showing that the prevalence of these states differs between CD and VD conditions in the expected direction: more efficient search in CD, where participants can learn to suppress the consistent distractor.
- Embed the suppression signal (VD-CD) directly in the model by allowing transition probabilities to depend on condition, and test whether this improves model fit.
- Visualize how the HMM-derived suppression score evolves across blocks, paralleling the standard behavioral analysis.

# Goals

This portfolio aims to figure out which emissions would be the best solution theoretically and computationally.


# Setup


``` r
rm(list = ls())

library(tidyverse)
```

```
## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.1     ✔ stringr   1.5.2
## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
```

``` r
library(readxl)
library(depmixS4)
```

```
## Loading required package: nnet
## Loading required package: MASS
## 
## Attaching package: 'MASS'
## 
## The following object is masked from 'package:dplyr':
## 
##     select
## 
## Loading required package: Rsolnp
## Loading required package: nlme
## 
## Attaching package: 'nlme'
## 
## The following object is masked from 'package:dplyr':
## 
##     collapse
```

``` r
library(knitr)
library(patchwork)
```

```
## 
## Attaching package: 'patchwork'
## 
## The following object is masked from 'package:MASS':
## 
##     area
```

``` r
select <- dplyr::select
filter <- dplyr::filter
```



``` r
# plot theme
axis_text_size <- 20
axis_tick_text_size <- 18
graph_color <- "black"
axis_tick_length <- 0.25
axis_tick_units <- "cm"
axis_thickness <- 1

manuscript_theme <- theme_classic() +
  theme(
    axis.line = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.title = element_text(size = axis_text_size),
    axis.text = element_text(colour = graph_color, size = axis_tick_text_size),
    axis.ticks = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.ticks.length.y = unit(axis_tick_length, axis_tick_units),
    axis.ticks.length.x = unit(axis_tick_length, axis_tick_units),
    legend.position = "top",
    text = element_text(size = axis_tick_text_size)
  )

# State colors
col_efficient <- "#1F77B4"
col_engaged <- "#D62728"
state_colors <- c("Efficient Search" = col_efficient,
                  "Distractor Engagement" = col_engaged)
```

# Data preparation

The fixation data come from the `fdata` sheet of the VST summary spreadsheet, which is already fully preprocessed: practice blocks removed (block_Norm 1-8 only), RT and SRT outliers excluded, correct trials only, central fixation excluded, and each fixation classified as Target, TCD, or Distractor.


``` r
fdata_file <- "summary/VST_DataSummary_SL_EyeTracking_Final.xlsx"
fdata <- read_excel(fdata_file, sheet = "fdata")
```


``` r
hmm_data <- fdata %>%
  mutate(
    subjnum = as.integer(subjnum),
    block = as.integer(block),
    block_Norm = as.integer(block_Norm),
    trial = as.integer(trial),
    saccindex = as.integer(saccindex),
    Dwell = as.numeric(CURRENT_FIX_DURATION),
    log_dur = log(as.numeric(CURRENT_FIX_DURATION)),
    obs = case_when(
      curritem == "Target" ~ 1L,
      curritem == "TCD" ~ 2L,
      curritem == "Distractor" ~ 3L
    ),
    obs_label = factor(curritem, levels = c("Target", "TCD", "Distractor")),
    condition = factor(condition, levels = c("CD", "VD")), # CD as reference level 
    TaskOrder = factor(
      ifelse(as.integer(TaskOrder) == 1, "VST_first", "RSVP_first"),
      levels = c("VST_first", "RSVP_first")
    )
  ) %>%
  group_by(subjnum) %>%
  mutate(
    trial_id = paste(subjnum, block, trial, sep = "_"),
    trial_num = dense_rank(interaction(block, trial))
  ) %>%
  ungroup() %>%
  filter(!is.na(obs), !is.na(log_dur), is.finite(log_dur)) %>%
  select(subjnum, TaskOrder, block, block_Norm, trial, trial_num, trial_id, condition, saccindex, curritem, obs, obs_label, Dwell, log_dur, CURRENT_FIX_X, CURRENT_FIX_Y) %>%
  arrange(subjnum, trial_num, saccindex)
```

## Descriptive Summary


``` r
n_subj <- length(unique(hmm_data$subjnum))

trials_per_subj <- hmm_data %>%
  distinct(subjnum, trial_id) %>% # One row per trial per participant
  count(subjnum) %>%
  summarise(M = mean(n), SD = sd(n), Min = min(n), Max = max(n))
trials_per_subj
```

```
## # A tibble: 1 × 4
##       M    SD   Min   Max
##   <dbl> <dbl> <int> <int>
## 1  235.  14.8   196   252
```

``` r
fix_per_trial <- hmm_data %>%
  count(trial_id) %>% # how many fixations in each trial
  summarise(M = mean(n), SD = sd(n), Min = min(n), Max = max(n))
fix_per_trial
```

```
## # A tibble: 1 × 4
##       M    SD   Min   Max
##   <dbl> <dbl> <int> <int>
## 1  3.15  1.15     1     7
```

The dataset includes 48 participants (24 start the VST first) contributing an average of 235 trials, with 3.15 fixations per trial on average.


``` r
obs_freq <- hmm_data %>%
  count(condition, curritem) %>% # count fixations by condition × item type
  group_by(condition) %>%
  mutate(prop = round(n / sum(n), 3)) %>% # proportion within each condition
  ungroup()

kable(obs_freq, caption = "Table 1. Fixation counts and proportions by condition and item type.")
```



Table: Table 1. Fixation counts and proportions by condition and item type.

|condition |curritem   |    n|  prop|
|:---------|:----------|----:|-----:|
|CD        |Distractor | 8926| 0.502|
|CD        |TCD        | 6549| 0.368|
|CD        |Target     | 2303| 0.130|
|VD        |Distractor | 8850| 0.497|
|VD        |TCD        | 6677| 0.375|
|VD        |Target     | 2269| 0.128|


``` r
obs_by_ord <- hmm_data %>%
  filter(saccindex <= 4) %>%
  count(condition, saccindex, curritem) %>%
  group_by(condition, saccindex) %>%
  mutate(prop = round(n / sum(n), 3)) %>%
  ungroup() %>%
  select(-n) %>%
  pivot_wider(names_from = curritem, values_from = prop)

kable(obs_by_ord, caption = "Table 2. Fixation proportions by ordinal position (first 4 fixations) and condition.")
```



Table: Table 2. Fixation proportions by ordinal position (first 4 fixations) and condition.

|condition | saccindex| Distractor|   TCD| Target|
|:---------|---------:|----------:|-----:|------:|
|CD        |         1|      0.502| 0.372|  0.126|
|CD        |         2|      0.519| 0.380|  0.101|
|CD        |         3|      0.500| 0.357|  0.143|
|CD        |         4|      0.476| 0.365|  0.160|
|VD        |         1|      0.502| 0.374|  0.124|
|VD        |         2|      0.511| 0.386|  0.103|
|VD        |         3|      0.493| 0.369|  0.138|
|VD        |         4|      0.469| 0.373|  0.158|

Table 1 shows the overall distribution of fixations across item types. Target fixations make up the largest share in both conditions, consistent with strong target-directed guidance. Table 2 breaks this down by ordinal position: the first fixation within a trial reveals the initial attentional capture pattern, while later fixations reflect corrective saccades. The key observation here is that item-type proportions are broadly similar across CD and VD, which is expected — the gaze-contingent design ensures that visual guidance is driven by the target color, not by the distractor's identity. Any condition differences in attentional allocation should emerge at the level of latent processing modes, which is what the HMM is designed to capture.

# Multinomial-Only HMMs (Item Type)

We pool CD and VD trials for model fitting because the hidden states represent general processing modes that are shared across conditions. The suppression signal will be captured as a condition difference in state prevalence, not as different emission profiles. Each trial is treated as an independent sequence, with sequence length equal to the number of fixation in that trial.

We start by fitting HMMs using only item type (Target, TCD, Distractor) as the emission variable, to see whether item type alone can separate attentional modes.

## 2-State Multinomial


``` r
# Create the factor emission variables - depmixS4 needs
hmm_data$obs_factor <- factor(hmm_data$obs, levels = 1:3,
                              labels = c("Target", "TCD", "Distractor"))

# How many fixations in each trial --> tells depmixS4 where sequences start/end
# Use rle on the row-ordered trial_id so seq_lengths matches the data row order
# (count() would sort alphabetically, which mismatches arrange(subjnum, trial_num)).
seq_lengths <- rle(as.character(hmm_data$trial_id))$lengths

# Fit 2-state multinomial with item type only 
set.seed(42)
mod2_cat <- depmix(obs_factor ~ 1,
                   data = hmm_data,
                   nstates = 2,
                   family = multinomial("identity"),
                   ntimes = seq_lengths)

fit2_cat <- fit(mod2_cat, verbose = FALSE)
```

```
## converged at iteration 1 with logLik: -34798.8
```


``` r
# Extract emission probabilities
extract_cat_emissions <- function(fit_model, K) {
  em <- data.frame(state = 1:K, p_target = NA, p_tcd = NA, p_distractor = NA)
  for (s in 1:K) {
    rp <- fit_model@response[[s]][[1]]@parameters$coefficients
    em$p_target[s] <- rp[1] # P(Target)
    em$p_tcd[s] <- rp[2] # P(TCD) 
    em$p_distractor[s] <- rp[3] # P(distractor)
  }
  em
}

em2_cat <- extract_cat_emissions(fit2_cat, 2) 

kable(em2_cat, digits = 3, caption = "Table 3a. Emission probabilities: 2-state multinomial model.")
```



Table: Table 3a. Emission probabilities: 2-state multinomial model.

| state| p_target| p_tcd| p_distractor|
|-----:|--------:|-----:|------------:|
|     1|    0.131| 0.373|        0.496|
|     2|    0.126| 0.371|        0.503|


``` r
em2_cat %>%
  mutate(state = factor(state)) %>%
  pivot_longer(cols = c(p_target, p_tcd, p_distractor),
               names_to = "item", values_to = "probability") %>%
  mutate(
    item = recode(item,
      "p_target" = "Target", "p_tcd" = "TCD", "p_distractor" = "Distractor"),
    item = factor(item, levels = c("Target", "TCD", "Distractor"))
  ) %>%
  ggplot(aes(x = item, y = probability, fill = state)) +
  geom_col(position = position_dodge(0.8), width = 0.7) +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  labs(x = "Item Type", y = "Emission Probability", fill = "State") +
  manuscript_theme
```

![plot of chunk unnamed-chunk-10](figure/unnamed-chunk-10-1.png)

As shown in Table 3a and the bar plot, the 2-state multinomial model produced nearly identical emission profiles across the two states. Both states show similar proportions of Target, TCD, and Distractor fixations, meaning the model is not finding meaningful state separation based on item type alone. This failure is theoretically informative: with only ~3.15 fixations per trial, there is not enough within-trial sequential variability in fixation location for the EM algorithm to distinguish different attentional modes. The item-type distribution is too homogeneous across fixations within a trial to support state separation.

## 3-State Multinomial

We shift to the 3-state model to see if adding a third state allows the model to find distinct attentional modes from item type alone.


``` r
# 3-state multinomial
set.seed(42)
mod3_cat <- depmix(obs_factor ~ 1,
                   data = hmm_data,
                   nstates = 3,
                   family = multinomial("identity"),
                   ntimes = seq_lengths)
fit3_cat <- fit(mod3_cat, verbose = FALSE)
```

```
## converged at iteration 1 with logLik: -34798.8
```


``` r
em3_cat <- extract_cat_emissions(fit3_cat, 3)

kable(em3_cat, digits = 3,
      caption = "Table 3b. Emission probabilities: 3-state multinomial model.")
```



Table: Table 3b. Emission probabilities: 3-state multinomial model.

| state| p_target| p_tcd| p_distractor|
|-----:|--------:|-----:|------------:|
|     1|    0.130| 0.370|        0.500|
|     2|    0.127| 0.374|        0.499|
|     3|    0.128| 0.372|        0.500|


``` r
em3_cat %>%
  mutate(state = factor(state)) %>%
  pivot_longer(cols = c(p_target, p_tcd, p_distractor),
               names_to = "item", values_to = "probability") %>%
  mutate(
    item = recode(item,
      "p_target" = "Target", "p_tcd" = "TCD", "p_distractor" = "Distractor"),
    item = factor(item, levels = c("Target", "TCD", "Distractor"))
  ) %>%
  ggplot(aes(x = item, y = probability, fill = state)) +
  geom_col(position = position_dodge(0.8), width = 0.7) +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  labs(x = "Item Type", y = "Emission Probability", fill = "State") +
  manuscript_theme
```

![plot of chunk unnamed-chunk-13](figure/unnamed-chunk-13-1.png)


``` r
cat_comp <- data.frame(
  Model = c("2-state multinomial", "3-state multinomial"),
  logLik = c(logLik(fit2_cat), logLik(fit3_cat)), # higher = better fit to data 
  AIC = c(AIC(fit2_cat), AIC(fit3_cat)), # lower = better
  BIC = c(BIC(fit2_cat), BIC(fit3_cat)) # lower = better
)

kable(cat_comp, digits = 1, caption = "Table 4. Model comparison for multinomial-only HMMs.")
```



Table: Table 4. Model comparison for multinomial-only HMMs.

|Model               |   logLik|     AIC|     BIC|
|:-------------------|--------:|-------:|-------:|
|2-state multinomial | -34798.8| 69611.6| 69670.9|
|3-state multinomial | -34798.8| 69625.6| 69744.3|

The 3-state multinomial model also fails to recover qualitatively distinct attentional modes from item type alone. As Table 3b and the bar plot show, all three states produce similar item-type distributions, with no state showing a clear specialization for target-directed fixations versus distractor capture. Table 4 provides a formal model comparison: while the 3-state model has a higher log-likelihood (as expected with more parameters), neither model achieves meaningful state separation in terms of emission profiles. This pattern confirms that fixation location alone — at least with the short trial lengths in this paradigm — cannot differentiate attentional modes. The critical missing signal is how long each fixation lasts, which motivates adding fixation duration as a second emission variable in the joint model below.


# Joint 2-State HMM (Item Type + Duration)

Adding fixation duration as a Gaussian emission (on log-transformed ms) gives the model the leverage to distinguish fast, efficient search from slower, distractor-engaged processing. Therefore, we fit a 2-state joint model with 10 random restarts to avoid local optima.


``` r
best_fit <- NULL # placeholder - no successful fit yet 
best_ll  <- -Inf # set to negative inifinity so any real logLik beats it

for (r in 1:10) { # 10 different random starting points
  set.seed(r * 7 + 13)  
  tryCatch({ 
    mod_joint <- depmix(
      list(obs_factor ~ 1, log_dur ~ 1), # two emissions: item type + log duration
      data = hmm_data,
      nstates = 2,
      family = list(multinomial("identity"), gaussian()),
      ntimes = seq_lengths # how many fixation in each trial 
    )
    this_fit <- fit(mod_joint, verbose = FALSE) # run EM algorithm to estimate parameters
    this_ll <- as.numeric(logLik(this_fit)) # log-likelihood 
    if (this_ll > best_ll) { # is this better than all previous restarts?
      best_ll <- this_ll # update best log-likelihood
      best_fit <- this_fit # save this model as current best
    }
  }, error = function(e) {message("Restart", r, "failed: ", e$message)}) # silently skip failed restarts
}
```

```
## converged at iteration 212 with logLik: -49085.37 
## converged at iteration 215 with logLik: -49085.37 
## converged at iteration 213 with logLik: -49085.37 
## converged at iteration 215 with logLik: -49085.37 
## converged at iteration 213 with logLik: -49085.37 
## converged at iteration 214 with logLik: -49085.37 
## converged at iteration 214 with logLik: -49085.37 
## converged at iteration 212 with logLik: -49085.37 
## converged at iteration 212 with logLik: -49085.37 
## converged at iteration 212 with logLik: -49085.37
```

``` r
fit_primary <- best_fit # after all 10 restarts, keep the single best model 
```


``` r
full_comp <- data.frame(
  Model = c("2-state multinomial (item only)",
            "3-state multinomial (item only)",
            "2-state joint (item + duration)"),
  logLik  = c(logLik(fit2_cat), logLik(fit3_cat), logLik(fit_primary)),
  AIC = c(AIC(fit2_cat), AIC(fit3_cat), AIC(fit_primary)),
  BIC = c(BIC(fit2_cat), BIC(fit3_cat), BIC(fit_primary))
)

kable(full_comp, digits = 1, caption = "Table 5. Full model comparison. The 2-state joint model is adopted as the primary model.")
```



Table: Table 5. Full model comparison. The 2-state joint model is adopted as the primary model.

|Model                           |   logLik|     AIC|     BIC|
|:-------------------------------|--------:|-------:|-------:|
|2-state multinomial (item only) | -34798.8| 69611.6| 69670.9|
|3-state multinomial (item only) | -34798.8| 69625.6| 69744.3|
|2-state joint (item + duration) | -49085.4| 98192.7| 98286.0|

Table 5 compares all three models. The 2-state joint model achieves a substantially higher log-likelihood than both multinomial-only models, and also has the lowest AIC and BIC, confirming that adding duration as a second emission variable dramatically improves model fit. This improvement is not simply due to having more parameters - the 2-state joint model has fewer parameters than the 3-state multinomial, yet fits the data far better. The duration emission provides the discriminative signal that item type alone could not: fast fixations on the target reflect efficient search, while slow fixations on non-target items reflect distractor engagement. The 2-state joint model is adopted as the primary model for all subsequent analyses.


## State Interpretation


``` r
# Emission probabilities (response 1 = multinomial, response 2 = Gaussian)

# table to hold emission params for each state
emission_df <- data.frame(
  state = 1:2,
  p_target = NA, p_tcd = NA, p_distractor = NA,
  mean_dur_ms = NA, sd_log_dur = NA
)

for (s in 1:2) { # loop over for both states
  rp_cat <- fit_primary@response[[s]][[1]]@parameters$coefficients # multinomial probs
  rp_gauss <- fit_primary@response[[s]][[2]]@parameters # Gaussian params
  emission_df$p_target[s] <- rp_cat[1] # P(fixating Target) in state s
  emission_df$p_tcd[s] <- rp_cat[2] # P(fixating TCD) in state s
  emission_df$p_distractor[s] <- rp_cat[3] # P(fixating Distractor) in state s
  emission_df$mean_dur_ms[s] <- exp(rp_gauss$coefficients) # back-transform log(ms) → ms
  emission_df$sd_log_dur[s] <- rp_gauss$sd # SD on log scale
}

# Label states - whichever has higher P(Target) = Efficient Search 
efficient_state <- which.max(emission_df$p_target) # state index with more target fixations
engaged_state <- setdiff(1:2, efficient_state) # the other state
emission_df$state_label <- ifelse(
  emission_df$state == efficient_state,
  "Efficient Search", "Distractor Engagement"
)

# 2x2 Transition matrix - 
trans_mat <- matrix(NA, 2, 2)
for (i in 1:2) {
  trans_mat[i, ] <- fit_primary@transition[[i]]@parameters$coefficients
}
colnames(trans_mat) <- rownames(trans_mat) <- emission_df$state_label

# Initial state probabilities - what state a trial most likely starts in
init_pars <- getpars(fit_primary) # all model parameters as a flat vector
init_probs <- init_pars[1:2] # first two = initial state probs
```


``` r
em_display <- emission_df %>%
  select(State = state_label,
         `P(Target)` = p_target,
         `P(TCD)` = p_tcd,
         `P(Distractor)` = p_distractor,
         `Mean Duration (ms)` = mean_dur_ms,
         `SD log(dur)` = sd_log_dur)

kable(em_display, digits = 3, caption = "Table 6. Emission parameters for each hidden state (joint model).")
```



Table: Table 6. Emission parameters for each hidden state (joint model).

|State                 | P(Target)| P(TCD)| P(Distractor)| Mean Duration (ms)| SD log(dur)|
|:---------------------|---------:|------:|-------------:|------------------:|-----------:|
|Efficient Search      |     0.311|  0.290|         0.399|            202.637|       0.605|
|Distractor Engagement |     0.000|  0.429|         0.571|            209.858|       0.189|


``` r
p_item <- emission_df %>%
  pivot_longer(cols = c(p_target, p_tcd, p_distractor),
               names_to = "item", values_to = "probability") %>%
  mutate(
    item = recode(item,
      "p_target" = "Target", "p_tcd" = "TCD", "p_distractor" = "Distractor"),
    item = factor(item, levels = c("Target", "TCD", "Distractor"))
  ) %>%
  ggplot(aes(x = item, y = probability, fill = state_label)) +
  geom_col(position = position_dodge(0.8), width = 0.7) +
  scale_fill_manual(values = state_colors) +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  labs(x = "Item Type", y = "Emission Probability", fill = "Hidden State") +
  manuscript_theme

p_dur <- emission_df %>%
  mutate(
    dur_lo = exp(log(mean_dur_ms) - sd_log_dur),
    dur_hi = exp(log(mean_dur_ms) + sd_log_dur)
  ) %>%
  ggplot(aes(x = state_label, y = mean_dur_ms, fill = state_label)) +
  geom_col(width = 0.6) +
  geom_errorbar(aes(ymin = dur_lo, ymax = dur_hi), width = 0.2, linewidth = 0.8) +
  geom_text(aes(label = sprintf("%.0f ms", mean_dur_ms)),
            vjust = -0.5, size = 5) +
  scale_fill_manual(values = state_colors) +
  labs(x = "Hidden State", y = "Mean Fixation Duration (ms)", fill = "Hidden State") +
  manuscript_theme +
  theme(legend.position = "none")

p_item + p_dur + plot_layout(widths = c(1.4, 1))
```

![plot of chunk unnamed-chunk-19](figure/unnamed-chunk-19-1.png)

The 2-state joint model recovered two interpretable states. The Efficient Search state was characterized by elevated P(Target) = 0.311 and shorter fixation duration (M = 203 ms), consistent with rapid target acquisition with minimal distractor interference. The Distractor Engagement state showed higher P(TCD) = 0.429 and P(Distractor) = 0.571, with longer fixation duration (*M* = 210 ms), reflecting slower processing of non-target items. The duration difference between states (7 ms) provided the primary discriminative signal.


``` r
kable(round(trans_mat, 3),
      caption = "Table 7. Transition matrix between hidden states.")
```



Table: Table 7. Transition matrix between hidden states.

|                      | Efficient Search| Distractor Engagement|
|:---------------------|----------------:|---------------------:|
|Efficient Search      |            0.478|                 0.522|
|Distractor Engagement |            0.392|                 0.608|


``` r
# Reshape transition matrix for heatmap plotting 
trans_long <- as.data.frame(trans_mat) %>%
  mutate(from = rownames(trans_mat)) %>%
  pivot_longer(-from, names_to = "to", values_to = "prob") %>%
  mutate(
    from = factor(from, levels = emission_df$state_label),
    to   = factor(to, levels = emission_df$state_label)
  )

ggplot(trans_long, aes(x = to, y = from, fill = prob)) +
  geom_tile(color = "white") +
  geom_text(aes(label = sprintf("%.2f", prob)),
            color = ifelse(trans_long$prob > 0.5, "white", "black"), size = 5) +
  scale_fill_gradient(low = "#EBF5FB", high = "#1B4F72", limits = c(0, 1)) +
  labs(x = "To State", y = "From State", fill = "P(transition)") +
  coord_equal() +
  manuscript_theme +
  theme(axis.ticks = element_blank())
```

![plot of chunk unnamed-chunk-21](figure/unnamed-chunk-21-1.png)

The transition matrix (Table 7) reveals that both states are highly self-persistent: once the oculomotor system enters Efficient Search, it tends to stay there for the remaining fixations in that trial, and likewise for Distractor Engagement. This means that the attentional mode on the first fixation largely determines the processing mode for the entire trial. The off-diagonal transition probabilities — the chance of switching from one state to the other mid-trial — are small, indicating that within-trial state switches are relatively rare. This is consistent with the idea that each trial begins with an initial attentional competition between the target and the singleton, and the outcome of that competition sets the processing mode for the rest of the trial (Theeuwes, 2010; Gaspelin & Luck, 2019).

The initial state probabilities were P(Efficient Search) = 0.396 and P(Distractor Engagement) = 0.604. These indicate the model's estimate of which state a trial is most likely to begin in, averaged across all trials and conditions.


# Validation: VD - CD State Occupancy (Suppression Score)

If the HMM captures meaningful attentional states, then participants should show more time in Efficient Search on CD trials — where they can learn to suppress the consistent distractor — than on VD trials. The VD - CD difference in P(Distractor Engagement) should be positive, reflecting more engagement with distractors when they cannot be predicted. This is the HMM analog of the standard behavioral suppression score.


``` r
# posterior state probs for every fixation
post <- depmixS4::posterior(fit_primary)
```

```
## Warning in .local(object, ...): Argument 'type' not specified and will default
## to 'viterbi'. This default may change in future releases of depmixS4. Please
## see ?posterior for alternative options.
```

``` r
hmm_data$p_efficient <- post[, paste0("S", efficient_state)] # P(Efficient) per fixation
hmm_data$p_engaged <- post[, paste0("S", engaged_state)] # P(Engaged) per fixation
hmm_data$decoded <- ifelse(post$state == efficient_state,
                                "Efficient Search", "Distractor Engagement") # most likely state 

# Trial-level: mean P(Efficient Search) per trial
trial_states <- hmm_data %>%
  group_by(subjnum, TaskOrder, trial_num, trial_id, condition, block_Norm) %>%
  summarise(
    p_efficient = mean(p_efficient), 
    p_engaged = mean(p_engaged),
    n_fix = n(),
    .groups = "drop"
  )

# Block-level averages
block_states <- trial_states %>%
  group_by(TaskOrder, condition, block_Norm) %>%
  summarise(
    M_efficient = mean(p_efficient),
    SE_efficient = sd(p_efficient) / sqrt(n()),
    M_engaged = mean(p_engaged),
    SE_engaged = sd(p_engaged) / sqrt(n()),
    .groups = "drop"
  )

# HMM suppression score: VD - CD in P(Distractor Engagement)
# For each participant × block, get mean P(Engaged) for CD and VD separately
hmm_suppress <- trial_states %>%
  group_by(subjnum, TaskOrder, block_Norm, condition) %>%
  summarise(M_engaged = mean(p_engaged), .groups = "drop") %>%
  pivot_wider(names_from = condition, values_from = M_engaged) %>%
  mutate(suppress_score = VD - CD)

# Block-level average suppression score
block_suppress <- hmm_suppress %>%
  group_by(TaskOrder, block_Norm) %>%
  summarise(
    M_score = mean(suppress_score, na.rm = TRUE),
    SE_score = sd(suppress_score, na.rm = TRUE) / sqrt(sum(!is.na(suppress_score))),
    .groups = "drop"
  )
```


``` r
overall_suppress <- hmm_suppress %>%
  group_by(TaskOrder) %>%
  summarise(
    M = mean(suppress_score, na.rm = TRUE),
    SD = sd(suppress_score, na.rm = TRUE),
    t = t.test(suppress_score)$statistic,
    df = t.test(suppress_score)$parameter,
    p = t.test(suppress_score)$p.value,
    .groups = "drop"
  )

kable(overall_suppress, digits = c(0, 3, 3, 2, 0, 4), caption = "Table 8. Overall HMM suppression score (VD - CD) by task order. Positive values indicate suppression.")
```



Table: Table 8. Overall HMM suppression score (VD - CD) by task order. Positive values indicate suppression.

|TaskOrder  |      M|    SD|     t|  df|      p|
|:----------|------:|-----:|-----:|---:|------:|
|VST_first  | -0.002| 0.071| -0.43| 191| 0.6662|
|RSVP_first | -0.002| 0.065| -0.36| 191| 0.7162|


``` r
ggplot(block_states,
       aes(x = block_Norm, y = M_engaged, color = condition,
           ymin = M_engaged - SE_engaged,
           ymax = M_engaged + SE_engaged)) +
  geom_line(linewidth = 1.1) +
  geom_point(size = 3) +
  geom_errorbar(width = 0.15, linewidth = 0.8) +
  facet_wrap(~ TaskOrder) +
  scale_color_manual(
    values = c("CD" = "#2196F3", "VD" = "#FF9800"),
    labels = c("CD" = "Consistent Distractor", "VD" = "Variable Distractor")) +
  labs(x = "Block", y = "P(Distractor Engagement)", color = "Condition") +
  manuscript_theme
```

![plot of chunk unnamed-chunk-24](figure/unnamed-chunk-24-1.png)


``` r
ggplot(block_suppress,
       aes(x = block_Norm, y = M_score,
           ymin = M_score - SE_score, ymax = M_score + SE_score,
           color = TaskOrder)) +
  geom_line(linewidth = 1.1) +
  geom_point(size = 3) +
  geom_errorbar(width = 0.15, linewidth = 0.8) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50", linewidth = 0.8) +
  labs(x = "Block", y = "Suppression Score (VD - CD)",
       color = "Task Order") +
  manuscript_theme
```

![plot of chunk unnamed-chunk-25](figure/unnamed-chunk-25-1.png)

Table 8 reports the overall HMM suppression score (VD − CD in P(Distractor Engagement)) by task order, tested against zero with a one-sample *t*-test. A positive score indicates that participants spent more time in the Distractor Engagement state on VD trials than CD trials — the expected direction if suppression of the consistent distractor has been learned.

The first figure above plots P(Distractor Engagement) across blocks, separately for CD and VD, faceted by task order. If suppression develops with experience, CD should show a steeper decline in P(Distractor Engagement) across blocks compared to VD, because participants can learn to suppress the predictable singleton in CD but not the unpredictable one in VD. The second figure plots the block-level suppression score (VD − CD) directly. Values above the dashed zero line indicate blocks where suppression was present. An upward trend across blocks would suggest that the suppression signal grows as participants accumulate experience with the consistent distractor.


# Condition-Dependent Transition Model

The post-hoc VD - CD comparison above treats the HMM as a preprocessing step: it converts fixation sequences into state occupancy proportions, and then the condition comparison happens outside the model. A more principled approach embeds the suppression signal directly in the model by allowing the transition probabilities to depend on condition. The emissions (what defines the states) remain pooled — the processing modes are the same across conditions — but the probability of transitioning into Efficient Search versus staying in Distractor Engagement can differ between CD and VD.

If learned suppression is present, the model should estimate that in CD trials, participants transition into Efficient Search more readily and are less likely to fall back into Distractor Engagement, relative to VD trials. The condition effect on transitions is the suppression signal expressed as a model parameter rather than a post-hoc subtraction.

We fit three models: (a) the baseline pooled model with no covariates on transitions (~ 1), (b) a model with condition as a covariate on transitions (~ condition), and (c) a model that also includes block to capture the learning trajectory (~ condition + block_Norm).


``` r
hmm_data$block_Norm_c <- scale(hmm_data$block_Norm, scale = FALSE)  # center block

# Model (b): condition-dependent transitions (joint emissions)
best_cond_fit <- NULL
best_cond_ll  <- -Inf
for (r in 1:10) {
  set.seed(r * 7 + 13)
  tryCatch({
    mod_cond <- depmix(
      list(obs_factor ~ 1, log_dur ~ 1),
      data = hmm_data,
      nstates = 2,
      family = list(multinomial("identity"), gaussian()),
      ntimes = seq_lengths,
      transition = ~ condition)
    this_fit <- fit(mod_cond, verbose = FALSE)
    this_ll <- as.numeric(logLik(this_fit))
    if (this_ll > best_cond_ll) {
      best_cond_ll <- this_ll
      best_cond_fit <- this_fit
    }
  }, error = function(e) {})
}
```

```
## converged at iteration 213 with logLik: -49083.84 
## converged at iteration 216 with logLik: -49083.84 
## converged at iteration 214 with logLik: -49083.84 
## converged at iteration 216 with logLik: -49083.84 
## converged at iteration 214 with logLik: -49083.84 
## converged at iteration 216 with logLik: -49083.84 
## converged at iteration 215 with logLik: -49083.84 
## converged at iteration 213 with logLik: -49083.84 
## converged at iteration 213 with logLik: -49083.84 
## converged at iteration 213 with logLik: -49083.84
```

``` r
fit_cond <- best_cond_fit

# Model (c): condition + block on transitions (joint emissions)
best_cb_fit <- NULL
best_cb_ll <- -Inf
for (r in 1:10) {
  set.seed(r * 7 + 13)
  tryCatch({
    mod_cb <- depmix(
      list(obs_factor ~ 1, log_dur ~ 1),
      data = hmm_data,
      nstates = 2,
      family = list(multinomial("identity"), gaussian()),
      ntimes = seq_lengths,
      transition = ~ condition + block_Norm_c)
    this_fit <- fit(mod_cb, verbose = FALSE)
    this_ll <- as.numeric(logLik(this_fit))
    if (this_ll > best_cb_ll) {
      best_cb_ll <- this_ll
      best_cb_fit <- this_fit
    }
  }, error = function(e) {})
}
```

```
## converged at iteration 223 with logLik: -49077.07 
## converged at iteration 226 with logLik: -49077.07 
## converged at iteration 224 with logLik: -49077.07 
## converged at iteration 226 with logLik: -49077.07 
## converged at iteration 224 with logLik: -49077.07 
## converged at iteration 226 with logLik: -49077.07 
## converged at iteration 226 with logLik: -49077.07 
## converged at iteration 223 with logLik: -49077.07 
## converged at iteration 223 with logLik: -49077.07 
## converged at iteration 223 with logLik: -49077.07
```

``` r
fit_cond_block <- best_cb_fit
```


``` r
cond_comp <- data.frame(
  Model = c("Baseline (transitions ~ 1)",
            "Condition (transitions ~ condition)",
            "Condition + Block (transitions ~ condition + block)"),
  logLik = c(as.numeric(logLik(fit_primary)),
             as.numeric(logLik(fit_cond)),
             as.numeric(logLik(fit_cond_block))),
  AIC = c(AIC(fit_primary), AIC(fit_cond), AIC(fit_cond_block)),
  BIC = c(BIC(fit_primary), BIC(fit_cond), BIC(fit_cond_block)),
  npar = c(length(getpars(fit_primary)),
           length(getpars(fit_cond)),
           length(getpars(fit_cond_block)))
)

kable(cond_comp, digits = 1,
      caption = "Table 9. Comparison of transition model specifications (all with joint emissions). Lower AIC/BIC = better fit.")
```



Table: Table 9. Comparison of transition model specifications (all with joint emissions). Lower AIC/BIC = better fit.

|Model                                               |   logLik|     AIC|     BIC| npar|
|:---------------------------------------------------|--------:|-------:|-------:|----:|
|Baseline (transitions ~ 1)                          | -49085.4| 98192.7| 98286.0|   16|
|Condition (transitions ~ condition)                 | -49083.8| 98193.7| 98303.9|   20|
|Condition + Block (transitions ~ condition + block) | -49077.1| 98184.1| 98311.3|   24|


``` r
# Print the raw structure of transition coefficients once so we can verify
# that the softmax helper below indexes the matrix the way depmixS4 stores it.
str(fit_cond@transition[[1]]@parameters$coefficients)
```

```
##  num [1:2, 1:2] 0 0 -0.3951 -0.0864
##  - attr(*, "dimnames")=List of 2
##   ..$ : chr [1:2] "(Intercept)" "conditionVD"
##   ..$ : chr [1:2] "St1" "St2"
```


``` r
# Compute transition probabilities for CD vs VD via multinomial-logit softmax.
# depmixS4 stores transition coefficients as an n_predictors x n_states matrix
# (rows = predictors [Intercept, conditionVD], cols = to-states). When the
# reference column is dropped (matrix has n_states - 1 cols), we re-insert a
# zero column so softmax gives the correct probabilities.
get_transition_probs <- function(fit_model, state_from, n_states = 2) {
  coef <- fit_model@transition[[state_from]]@parameters$coefficients
  if (!is.matrix(coef)) coef <- matrix(coef, ncol = 1)
  if (ncol(coef) < n_states) coef <- cbind(0, coef)  # reference = first to-state

  X_cd <- matrix(c(1, 0), nrow = 1)  # (Intercept, conditionVD = 0)
  X_vd <- matrix(c(1, 1), nrow = 1)  # (Intercept, conditionVD = 1)

  eta_cd <- as.numeric(X_cd %*% coef)
  eta_vd <- as.numeric(X_vd %*% coef)

  p_cd <- exp(eta_cd) / sum(exp(eta_cd))
  p_vd <- exp(eta_vd) / sum(exp(eta_vd))

  data.frame(
    from = state_from,
    CD_to_S1 = p_cd[1], CD_to_S2 = p_cd[2],
    VD_to_S1 = p_vd[1], VD_to_S2 = p_vd[2]
  )
}

trans_cd_vd <- bind_rows(
  get_transition_probs(fit_cond, 1),
  get_transition_probs(fit_cond, 2)
)

# Echo the per-state coefficients on the linear-predictor scale for inspection.
for (s in 1:2) {
  coef_s <- fit_cond@transition[[s]]@parameters$coefficients
  if (!is.matrix(coef_s)) coef_s <- matrix(coef_s, ncol = 1)
  cat(sprintf("From State %d (%s):\n", s, emission_df$state_label[s]))
  print(round(coef_s, 3))
  cat("\n")
}
```

```
## From State 1 (Efficient Search):
##             St1    St2
## (Intercept)   0 -0.395
## conditionVD   0 -0.086
## 
## From State 2 (Distractor Engagement):
##             St1    St2
## (Intercept)   0 -0.157
## conditionVD   0  0.145
```

``` r
# Display table
s1_label <- emission_df$state_label[1]
s2_label <- emission_df$state_label[2]

trans_display <- data.frame(
  `From State` = emission_df$state_label,
  check.names = FALSE
)
trans_display[[paste0("CD -> ", s1_label)]] <- c(trans_cd_vd$CD_to_S1[1], trans_cd_vd$CD_to_S1[2])
trans_display[[paste0("CD -> ", s2_label)]] <- c(trans_cd_vd$CD_to_S2[1], trans_cd_vd$CD_to_S2[2])
trans_display[[paste0("VD -> ", s1_label)]] <- c(trans_cd_vd$VD_to_S1[1], trans_cd_vd$VD_to_S1[2])
trans_display[[paste0("VD -> ", s2_label)]] <- c(trans_cd_vd$VD_to_S2[1], trans_cd_vd$VD_to_S2[2])

kable(trans_display, digits = 3,
      caption = "Table 10. Transition probabilities by condition. If suppression is present, CD should show higher probability of transitioning into Efficient Search.")
```



Table: Table 10. Transition probabilities by condition. If suppression is present, CD should show higher probability of transitioning into Efficient Search.

|From State            | CD -> Efficient Search| CD -> Distractor Engagement| VD -> Efficient Search| VD -> Distractor Engagement|
|:---------------------|----------------------:|---------------------------:|----------------------:|---------------------------:|
|Efficient Search      |                  0.597|                       0.403|                  0.618|                       0.382|
|Distractor Engagement |                  0.539|                       0.461|                  0.503|                       0.497|


``` r
trans_plot_df <- data.frame(
  from = rep(emission_df$state_label, each = 4),
  to = rep(rep(emission_df$state_label, each = 2), 2),
  condition = rep(c("CD", "VD"), 4),
  prob = c(
    trans_cd_vd$CD_to_S1[1], trans_cd_vd$VD_to_S1[1],
    trans_cd_vd$CD_to_S2[1], trans_cd_vd$VD_to_S2[1],
    trans_cd_vd$CD_to_S1[2], trans_cd_vd$VD_to_S1[2],
    trans_cd_vd$CD_to_S2[2], trans_cd_vd$VD_to_S2[2]
  )
)

ggplot(trans_plot_df,
       aes(x = condition, y = prob, fill = condition)) +
  geom_col(width = 0.6) +
  geom_text(aes(label = sprintf("%.3f", prob)),
            vjust = -0.5, size = 4) +
  facet_grid(from ~ to,
             labeller = labeller(
               from = setNames(paste("From:", emission_df$state_label),
                               emission_df$state_label),
               to = setNames(paste("To:", emission_df$state_label),
                               emission_df$state_label)
             )) +
  scale_fill_manual(
    values = c("CD" = "#2196F3", "VD" = "#FF9800"),
    labels = c("CD" = "Consistent Distractor", "VD" = "Variable Distractor")) +
  ylim(0, 1.05) +
  labs(x = "Condition", y = "Transition Probability", fill = "Condition") +
  manuscript_theme +
  theme(strip.text = element_text(size = 14))
```

![plot of chunk unnamed-chunk-30](figure/unnamed-chunk-30-1.png)


``` r
# Likelihood ratio test: does adding condition to transitions improve fit?
lr_stat <- -2 * (as.numeric(logLik(fit_primary)) - as.numeric(logLik(fit_cond)))
lr_df <- length(getpars(fit_cond)) - length(getpars(fit_primary))
lr_p <- pchisq(lr_stat, df = lr_df, lower.tail = FALSE)
```

Table 9 compares the three transition model specifications. The condition-dependent model adds two parameters (one VD effect per state's transition row), while the condition + block model adds two more. Lower AIC/BIC indicates better fit after accounting for model complexity.

Table 10 shows the actual transition probabilities for CD and VD conditions, computed by applying the inverse logit to the model coefficients. If suppression is present, CD trials should show a higher probability of transitioning into (or staying in) Efficient Search compared to VD trials. The faceted bar plot visualizes these differences: each panel shows transitions from one state to another, comparing CD (blue) and VD (orange). The key panels to examine are "From: Distractor Engagement → To: Efficient Search" (does CD show higher recovery probability?) and "From: Efficient Search → To: Efficient Search" (does CD show higher persistence in the efficient state?).

A likelihood ratio test comparing the baseline model (transitions ~ 1) to the condition-dependent model (transitions ~ condition) yielded $\chi^2$(4) = 3.05, *p* = 0.5495. This suggests that the condition effect on transitions was not statistically significant at the model level. This does not necessarily mean suppression is absent — the post-hoc occupancy comparison may still reveal meaningful differences at the block level, and the effect may be too subtle to detect within the transition structure given the short trial lengths (~3 fixations).


# Learning Trajectories


``` r
ggplot(block_states,
       aes(x = block_Norm, y = M_efficient, color = condition,
           linetype = TaskOrder,
           ymin = M_efficient - SE_efficient,
           ymax = M_efficient + SE_efficient)) +
  geom_line(linewidth = 1.1) +
  geom_point(size = 3) +
  geom_errorbar(width = 0.15, linewidth = 0.8) +
  scale_color_manual(
    values = c("CD" = "#2196F3", "VD" = "#FF9800"),
    labels = c("CD" = "Consistent Distractor", "VD" = "Variable Distractor")) +
  labs(x = "Block", y = "P(Efficient Search)",
       color = "Condition", linetype = "Task Order") +
  manuscript_theme
```

![plot of chunk unnamed-chunk-32](figure/unnamed-chunk-32-1.png)


``` r
example_subj <- sort(unique(hmm_data$subjnum))[1]

trial_states %>%
  filter(subjnum == example_subj) %>%
  ggplot(aes(x = trial_num, y = p_efficient, color = condition)) +
  geom_point(alpha = 0.5, size = 1.5) +
  geom_smooth(method = "loess", se = TRUE, span = 0.3, linewidth = 1.1) +
  scale_color_manual(
    values = c("CD" = "#2196F3", "VD" = "#FF9800"),
    labels = c("CD" = "Consistent Distractor", "VD" = "Variable Distractor")) +
  ylim(0, 1) +
  labs(x = "Trial Number", y = "P(Efficient Search)", color = "Condition") +
  manuscript_theme
```

```
## `geom_smooth()` using formula = 'y ~ x'
```

![plot of chunk unnamed-chunk-33](figure/unnamed-chunk-33-1.png)

The first figure shows the group-level learning trajectory: P(Efficient Search) across blocks for CD and VD, with separate line types for VST-first and RSVP-first groups. If suppression is learned, P(Efficient Search) should increase across blocks for CD (as participants learn to suppress the consistent distractor and shift toward efficient target-directed processing), while VD should remain relatively flat or show a smaller increase. The gap between CD and VD lines at later blocks reflects the magnitude of the learned suppression effect.

The second figure shows a single example participant's trial-by-trial P(Efficient Search) trajectory, smoothed with a LOESS curve. This illustrates the kind of individual-level variability that the group-level averages mask: some participants may show a rapid shift toward Efficient Search, while others may fluctuate between states throughout the experiment. This between-participant variability in learning dynamics is what motivates the participant-level feature extraction in Stage 2 (Portfolio 11).


# Save Output


``` r
if (!dir.exists("output")) dir.create("output")

write_csv(hmm_data %>%
            select(subjnum, TaskOrder, block, block_Norm, trial, trial_num, trial_id, condition, saccindex, curritem, obs, Dwell, log_dur, p_efficient, p_engaged, decoded), "output/hmm_vst_fixation_data.csv")

write_csv(trial_states, "output/hmm_vst_trial_states.csv")
write_csv(block_states, "output/hmm_block_states.csv")
write_csv(hmm_suppress, "output/hmm_suppression_scores.csv")
write_csv(emission_df, "output/hmm_emission_params.csv")
write_csv(trans_display, "output/hmm_transition_by_condition.csv")
```

