---
title: "Portfolio 12: HMM Stage 3 - Transfer Prediction (VST → RSVP)"
---

# Background

Portfolios 10 and 11 established that a 2-state joint HMM (item type + fixation duration) recovers two attentional modes — Efficient Search and Distractor Engagement — and that the VD−CD difference in state prevalence captures the learned distractor suppression signal. Portfolio 11 extracted five participant-level features from the VST-first group (n = 24) that quantify how quickly and how completely each individual learned to suppress the consistent distractor:

- **Learning slope**: rate of increase in P(Efficient Search) across trials.
- **Transition trial**: the trial at which the 5-trial rolling mean of P(Efficient Search) first exceeds 0.50.
- **End-state P(Efficient Search)**: mean P(Efficient Search) in the final experimental block.
- **Overall suppression score**: mean VD−CD difference in P(Distractor Engagement) across blocks.
- **Suppression growth**: late − early change in the suppression score.

The central question for Stage 3 is whether these HMM-derived individual differences in VST suppression learning predict cross-task transfer to the RSVP task. The VST-first group completed the Visual Search Task before the RSVP task, so any relationship between VST learning features and RSVP outcomes would constitute evidence that the latent suppression process captured by the HMM generalizes beyond the training task.

The primary RSVP transfer outcome is **Blink_CD** — the attentional blink magnitude for the consistent distractor color, computed as the difference in T2 accuracy between lag 8 and lag 2. A smaller blink indicates better processing of T2 when the distractor color is the one that was consistently paired with a distractor location during the VST. If learned suppression transfers, participants who showed stronger or faster suppression learning in the VST should show a reduced attentional blink for the consistent distractor color in the RSVP task.

This approach follows the logic of individual-differences transfer designs used in the learned attention literature, where the strength of statistical learning during training predicts the magnitude of transfer effects in a novel task (Britton & Anderson, 2020; Feldmann-Wüstefeld & Schubö, 2016; Won & Leber, 2016).


# Goals

1. Load the participant-level HMM features from Portfolio 11 and the RSVP transfer outcomes, and merge by participant.
2. Examine descriptive statistics and distributions of the RSVP outcome (Blink_CD) and all HMM predictors.
3. Run bivariate correlations between each HMM feature and Blink_CD to identify which aspects of suppression learning are associated with transfer.
4. Fit a multiple regression with the most promising predictors to test their joint and unique contributions.
5. Visualize the key predictor–outcome relationships.
6. Evaluate assumptions (normality, influential cases) and report results in APA style.


# Setup


``` r
rm(list = ls())

library(tidyverse)
library(readxl)
library(knitr)
library(patchwork)
library(car)       # for VIF in regression diagnostics

select <- dplyr::select
filter <- dplyr::filter
```



``` r
# Plot theme (matching manuscript style from p10/p11)
axis_text_size <- 20
axis_tick_text_size <- 18
graph_color <- "black"
axis_tick_length <- 0.25
axis_tick_units <- "cm"
axis_thickness <- 1

manuscript_theme <- theme_classic() +
  theme(
    axis.line = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.title = element_text(size = axis_text_size),
    axis.text = element_text(colour = graph_color, size = axis_tick_text_size),
    axis.ticks = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.ticks.length.y = unit(axis_tick_length, axis_tick_units),
    axis.ticks.length.x = unit(axis_tick_length, axis_tick_units),
    legend.position = "top",
    text = element_text(size = axis_tick_text_size)
  )

# Consistent color palette
col_efficient <- "#1F77B4"
col_engaged <- "#D62728"
```


# Data Loading and Merging

## Load HMM Features (from Portfolio 11)


``` r
# Participant-level HMM features extracted in p11 (VST-first group, n = 24)
hmm_features <- read_csv("output/stage2_participant_features_vst_first.csv",
                         show_col_types = FALSE)

cat(sprintf("HMM features loaded: %d participants, %d features\n",
            nrow(hmm_features), ncol(hmm_features) - 1))
```

```
## HMM features loaded: 24 participants, 16 features
```


## Load RSVP Transfer Outcomes


``` r
# RSVP accuracy data — ACC sheet contains all participants
rsvp_acc <- read_excel(
  "summary/RSVP_DataSummary_SL_EyeTracking_Final.xlsx",
  sheet = "ACC"
)

# Filter to VST-first group (Order == "VST_RSVP")
rsvp_vst <- rsvp_acc %>%
  filter(Order == "VST_RSVP") %>%
  mutate(subjnum = as.integer(subjnum))

cat(sprintf("RSVP data loaded: %d VST-first participants\n", nrow(rsvp_vst)))
```

```
## RSVP data loaded: 24 VST-first participants
```

The RSVP dataset contains T2 accuracy for each condition (CD, ND, VCD_Match, VCD_Mismatch) at two lags (2 and 8), along with pre-computed attentional blink scores (Blink = lag 8 − lag 2 accuracy). The primary outcome is **Blink_CD**: the attentional blink magnitude for the consistent distractor color.


## Merge Datasets


``` r
# Merge HMM features with RSVP outcomes by subject number
transfer_data <- hmm_features %>%
  inner_join(rsvp_vst, by = "subjnum")

cat(sprintf("Merged dataset: %d participants with both HMM features and RSVP outcomes\n",
            nrow(transfer_data)))
```

```
## Merged dataset: 24 participants with both HMM features and RSVP outcomes
```

``` r
# Check for any participants lost in the merge
hmm_only <- setdiff(hmm_features$subjnum, rsvp_vst$subjnum)
rsvp_only <- setdiff(rsvp_vst$subjnum, hmm_features$subjnum)
if (length(hmm_only) > 0) cat("  Participants in HMM but not RSVP:", hmm_only, "\n")
if (length(rsvp_only) > 0) cat("  Participants in RSVP but not HMM:", rsvp_only, "\n")
if (length(hmm_only) == 0 & length(rsvp_only) == 0) cat("  All participants matched.\n")
```

```
##   All participants matched.
```


# Descriptive Statistics

## RSVP Outcome: Blink_CD


``` r
# Summary of attentional blink scores
blink_summary <- transfer_data %>%
  summarise(
    across(c(Blink_CD, Blink_ND, Blink_VD_Match, Blink_VD_Mismatch),
           list(M = ~mean(., na.rm = TRUE),
                SD = ~sd(., na.rm = TRUE),
                Min = ~min(., na.rm = TRUE),
                Max = ~max(., na.rm = TRUE)),
           .names = "{.col}_{.fn}")
  ) %>%
  pivot_longer(everything(),
               names_to = c("measure", "stat"),
               names_pattern = "(.+)_(M|SD|Min|Max)") %>%
  pivot_wider(names_from = stat, values_from = value)
```

```
## Warning: Values from `value` are not uniquely identified; output will contain list-cols.
## • Use `values_fn = list` to suppress this warning.
## • Use `values_fn = {summary_fun}` to summarise duplicates.
## • Use the following dplyr code to identify duplicates.
##   {data} |>
##   dplyr::summarise(n = dplyr::n(), .by = c(measure, stat)) |>
##   dplyr::filter(n > 1L)
```

``` r
kable(blink_summary, digits = 3,
      caption = "Table 1. Descriptive statistics for RSVP attentional blink scores (VST-first group).")
```



Table: Table 1. Descriptive statistics for RSVP attentional blink scores (VST-first group).

|measure           |M                                   |SD         |
|:-----------------|:-----------------------------------|:----------|
|Blink_CD          |0.06312693, -0.08494208, 0.23865546 |0.1021727  |
|Blink_ND          |0.05790576, -0.04712405, 0.19504644 |0.04487119 |
|Blink_VD_Match    |0.07318922, -0.35714286, 0.60000000 |0.235381   |
|Blink_VD_Mismatch |0.06016576, -0.24137931, 0.33625731 |0.1252788  |


``` r
ggplot(transfer_data, aes(x = Blink_CD)) +
  geom_histogram(binwidth = 0.05, fill = col_efficient, color = "white", alpha = 0.8) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray40") +
  geom_vline(xintercept = mean(transfer_data$Blink_CD, na.rm = TRUE),
             linetype = "solid", color = col_engaged, linewidth = 1) +
  labs(x = "Blink_CD (Lag 8 − Lag 2 Accuracy)",
       y = "Count") +
  annotate("text", x = mean(transfer_data$Blink_CD, na.rm = TRUE), y = Inf,
           label = "Mean", vjust = 2, hjust = -0.2, color = col_engaged, size = 5) +
  manuscript_theme
```

![Figure 1. Distribution of attentional blink magnitude for the consistent distractor color (Blink_CD). Each bar represents a VST-first participant. Positive values indicate a standard attentional blink (better accuracy at lag 8 than lag 2); negative values indicate a reversed blink.](figure/blink-distribution-1.png)


## HMM Predictor Summary


``` r
# Key predictors for transfer regression
predictor_summary <- transfer_data %>%
  summarise(
    across(c(learning_slope, transition_trial, end_p_efficient,
             overall_suppress, suppress_growth),
           list(M = ~mean(., na.rm = TRUE),
                SD = ~sd(., na.rm = TRUE)),
           .names = "{.col}_{.fn}")
  ) %>%
  pivot_longer(everything(),
               names_to = c("feature", "stat"),
               names_pattern = "(.+)_(M|SD)") %>%
  pivot_wider(names_from = stat, values_from = value)

kable(predictor_summary, digits = 4,
      caption = "Table 2. Descriptive statistics for HMM-derived predictors (VST-first group).")
```



Table: Table 2. Descriptive statistics for HMM-derived predictors (VST-first group).

|feature          |        M|      SD|
|:----------------|--------:|-------:|
|learning_slope   |  -0.0001|  0.0002|
|transition_trial | 122.8824| 82.9065|
|end_p_efficient  |   0.2967|  0.0555|
|overall_suppress |  -0.0032|  0.0238|
|suppress_growth  |   0.0005|  0.0555|


# Bivariate Correlations

We first examine individual Pearson correlations between each HMM feature and Blink_CD. This step identifies which features show the strongest zero-order relationships with transfer before entering them into a multiple regression.


``` r
# Define predictors
predictors <- c("learning_slope", "transition_trial", "end_p_efficient",
                "overall_suppress", "suppress_growth")

predictor_labels <- c(
  learning_slope = "Learning Slope",
  transition_trial = "Transition Trial",
  end_p_efficient = "End-State P(Efficient)",
  overall_suppress = "Overall Suppression",
  suppress_growth = "Suppression Growth"
)

# Run bivariate correlations
cor_results <- map_dfr(predictors, function(pred) {
  # Remove NAs for this predictor (transition_trial may have NAs)
  d <- transfer_data %>%
    select(Blink_CD, all_of(pred)) %>%
    drop_na()

  ct <- cor.test(d[[pred]], d$Blink_CD)

  tibble(
    Predictor = predictor_labels[pred],
    variable = pred,
    r = ct$estimate,
    t = ct$statistic,
    df = ct$parameter,
    p = ct$p.value,
    CI_lower = ct$conf.int[1],
    CI_upper = ct$conf.int[2],
    n = nrow(d)
  )
})

kable(cor_results %>% select(Predictor, n, r, t, df, p, CI_lower, CI_upper),
      digits = c(0, 0, 3, 2, 0, 4, 3, 3),
      caption = "Table 3. Bivariate Pearson correlations between HMM features and Blink_CD.",
      col.names = c("Predictor", "n", "r", "t", "df", "p", "95% CI Lower", "95% CI Upper"))
```



Table: Table 3. Bivariate Pearson correlations between HMM features and Blink_CD.

|Predictor              |  n|      r|     t| df|      p| 95% CI Lower| 95% CI Upper|
|:----------------------|--:|------:|-----:|--:|------:|------------:|------------:|
|Learning Slope         | 24| -0.350| -1.75| 22| 0.0934|       -0.660|        0.062|
|Transition Trial       | 17|  0.110|  0.43| 15| 0.6730|       -0.391|        0.561|
|End-State P(Efficient) | 24| -0.363| -1.83| 22| 0.0815|       -0.668|        0.048|
|Overall Suppression    | 24|  0.233|  1.12| 22| 0.2735|       -0.188|        0.582|
|Suppression Growth     | 24|  0.188|  0.90| 22| 0.3801|       -0.233|        0.549|


``` r
# Count significant and trending predictors
sig_predictors <- cor_results %>% filter(p < .05)
trend_predictors <- cor_results %>% filter(p >= .05 & p < .10)

n_sig <- nrow(sig_predictors)
n_trend <- nrow(trend_predictors)

# Identify strongest predictor
strongest <- cor_results %>% arrange(p) %>% slice(1)
```


## Scatterplots: Each HMM Feature × Blink_CD


``` r
scatter_data <- transfer_data %>%
  select(subjnum, Blink_CD, all_of(predictors)) %>%
  pivot_longer(cols = all_of(predictors),
               names_to = "feature", values_to = "value") %>%
  mutate(feature_label = unname(predictor_labels[feature]))

ggplot(scatter_data, aes(x = value, y = Blink_CD)) +
  geom_point(size = 2.5, color = "gray35", alpha = 0.8) +
  geom_smooth(method = "lm", se = TRUE,
              color = "black", fill = "gray80", linewidth = 1) +
  facet_wrap(~ feature_label, scales = "free_x", ncol = 3) +
  labs(x = "HMM Feature Value", y = "Blink_CD") +
  manuscript_theme +
  theme(strip.text = element_text(size = 14))
```

```
## `geom_smooth()` using formula = 'y ~ x'
```

```
## Warning: Removed 7 rows containing non-finite outside the scale range
## (`stat_smooth()`).
```

```
## Warning: Removed 7 rows containing missing values or values outside the scale range
## (`geom_point()`).
```

![Figure 2. Bivariate relationships between each HMM feature and Blink_CD. Each point is one VST-first participant. The regression line (with 95% CI band) shows the direction and strength of the linear association. Stronger suppression learning during VST (e.g., steeper learning slope, higher end-state efficiency) should predict a smaller attentional blink for the consistent distractor color in the RSVP task.](figure/scatter-all-1.png)


# Predictor Intercorrelations

Before fitting the multiple regression, we check intercorrelations among predictors to assess potential multicollinearity.


``` r
pred_matrix <- transfer_data %>%
  select(all_of(predictors)) %>%
  drop_na()

cor_matrix <- cor(pred_matrix, use = "pairwise.complete.obs")

kable(round(cor_matrix, 3),
      caption = "Table 4. Intercorrelation matrix among HMM predictors.")
```



Table: Table 4. Intercorrelation matrix among HMM predictors.

|                 | learning_slope| transition_trial| end_p_efficient| overall_suppress| suppress_growth|
|:----------------|--------------:|----------------:|---------------:|----------------:|---------------:|
|learning_slope   |          1.000|            0.235|           0.359|            0.140|          -0.425|
|transition_trial |          0.235|            1.000|          -0.230|            0.479|           0.422|
|end_p_efficient  |          0.359|           -0.230|           1.000|           -0.286|          -0.607|
|overall_suppress |          0.140|            0.479|          -0.286|            1.000|           0.396|
|suppress_growth  |         -0.425|            0.422|          -0.607|            0.396|           1.000|


``` r
cor_long <- as.data.frame(as.table(cor_matrix)) %>%
  rename(Var1 = Var1, Var2 = Var2, r = Freq) %>%
  mutate(
    Var1 = unname(predictor_labels[as.character(Var1)]),
    Var2 = unname(predictor_labels[as.character(Var2)])
  )

ggplot(cor_long, aes(x = Var1, y = Var2, fill = r)) +
  geom_tile(color = "white") +
  geom_text(aes(label = sprintf("%.2f", r)), size = 4) +
  scale_fill_gradient2(low = col_engaged, mid = "white", high = col_efficient,
                       midpoint = 0, limits = c(-1, 1)) +
  labs(x = NULL, y = NULL, fill = "r") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

![Figure 3. Heatmap of intercorrelations among HMM predictors. Darker blue = stronger positive correlation; darker red = stronger negative correlation. High intercorrelations (|r| > .70) would signal multicollinearity concerns for the multiple regression.](figure/correlation-heatmap-1.png)


# Multiple Regression: HMM Features Predicting Blink_CD

We fit a multiple regression entering all five HMM features as simultaneous predictors of Blink_CD. This tests whether the features carry unique predictive information about transfer beyond their shared variance.


``` r
# Fit the full model (listwise deletion for transition_trial NAs)
reg_data <- transfer_data %>%
  select(subjnum, Blink_CD, all_of(predictors)) %>%
  drop_na()

cat(sprintf("Regression sample: n = %d (after excluding participants with missing transition_trial)\n",
            nrow(reg_data)))
```

```
## Regression sample: n = 17 (after excluding participants with missing transition_trial)
```

``` r
model_full <- lm(Blink_CD ~ learning_slope + transition_trial +
                   end_p_efficient + overall_suppress + suppress_growth,
                 data = reg_data)

summary(model_full)
```

```
## 
## Call:
## lm(formula = Blink_CD ~ learning_slope + transition_trial + end_p_efficient + 
##     overall_suppress + suppress_growth, data = reg_data)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.172317 -0.035390  0.000403  0.052985  0.165013 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(>|t|)
## (Intercept)       1.397e-01  1.885e-01   0.741    0.474
## learning_slope   -9.542e+01  1.576e+02  -0.606    0.557
## transition_trial  6.668e-05  4.148e-04   0.161    0.875
## end_p_efficient  -3.511e-01  5.747e-01  -0.611    0.554
## overall_suppress  6.424e-01  1.189e+00   0.540    0.600
## suppress_growth  -1.246e-01  6.918e-01  -0.180    0.860
## 
## Residual standard error: 0.1047 on 11 degrees of freedom
## Multiple R-squared:  0.1463,	Adjusted R-squared:  -0.2418 
## F-statistic: 0.377 on 5 and 11 DF,  p-value: 0.8543
```


## Regression Diagnostics


``` r
# Variance Inflation Factors
vif_values <- vif(model_full)
cat("Variance Inflation Factors:\n")
```

```
## Variance Inflation Factors:
```

``` r
print(round(vif_values, 2))
```

```
##   learning_slope transition_trial  end_p_efficient overall_suppress 
##             1.77             1.73             1.64             1.47 
##  suppress_growth 
##             2.49
```

``` r
vif_concern <- any(vif_values > 5)
if (vif_concern) {
  cat("\nWARNING: VIF > 5 detected — multicollinearity may inflate standard errors.\n")
} else {
  cat("\nAll VIFs < 5 — no severe multicollinearity concerns.\n")
}
```

```
## 
## All VIFs < 5 — no severe multicollinearity concerns.
```


``` r
par(mfrow = c(2, 2))
plot(model_full)
```

![Figure 4. Regression diagnostic plots. Top-left: residuals vs. fitted (check for non-linearity and heteroscedasticity). Top-right: Q-Q plot (check for normality of residuals). Bottom-left: scale-location (check for homoscedasticity). Bottom-right: residuals vs. leverage (identify influential cases with high Cook's distance).](figure/diagnostic-plots-1.png)

``` r
par(mfrow = c(1, 1))
```


``` r
# Identify influential cases (Cook's D > 4/n)
cooks_d <- cooks.distance(model_full)
threshold <- 4 / nrow(reg_data)
influential <- which(cooks_d > threshold)

if (length(influential) > 0) {
  cat(sprintf("Influential cases (Cook's D > %.3f):\n", threshold))
  cat("  Row indices:", paste(influential, collapse = ", "), "\n")
  cat("  Subject numbers:", paste(reg_data$subjnum[influential], collapse = ", "), "\n")
  cat("  Cook's D values:", paste(round(cooks_d[influential], 3), collapse = ", "), "\n")
} else {
  cat("No influential cases detected.\n")
}
```

```
## Influential cases (Cook's D > 0.235):
##   Row indices: 5, 9 
##   Subject numbers: 9, 23 
##   Cook's D values: 0.477, 0.72
```


## Standardized Coefficients


``` r
# Standardize all variables for comparable effect sizes
reg_data_z <- reg_data %>%
  mutate(across(c(Blink_CD, all_of(predictors)), scale))

model_std <- lm(Blink_CD ~ learning_slope + transition_trial +
                  end_p_efficient + overall_suppress + suppress_growth,
                data = reg_data_z)

# Extract standardized coefficients
std_coefs <- broom::tidy(model_std) %>%
  filter(term != "(Intercept)") %>%
  mutate(term = unname(predictor_labels[term]))

kable(std_coefs, digits = c(0, 3, 3, 2, 4),
      caption = "Table 5. Standardized regression coefficients predicting Blink_CD from HMM features.",
      col.names = c("Predictor", "β", "SE", "t", "p"))
```



Table: Table 5. Standardized regression coefficients predicting Blink_CD from HMM features.

|Predictor              |      β|    SE|     t|      p|
|:----------------------|------:|-----:|-----:|------:|
|Learning Slope         | -0.225| 0.371| -0.61| 0.5571|
|Transition Trial       |  0.059| 0.366|  0.16| 0.8752|
|End-State P(Efficient) | -0.218| 0.357| -0.61| 0.5537|
|Overall Suppression    |  0.183| 0.338|  0.54| 0.5998|
|Suppression Growth     | -0.079| 0.440| -0.18| 0.8603|


``` r
std_coefs_ci <- broom::tidy(model_std, conf.int = TRUE) %>%
  filter(term != "(Intercept)") %>%
  mutate(term = unname(predictor_labels[term]),
         term = fct_reorder(term, abs(estimate)))

ggplot(std_coefs_ci, aes(x = estimate, y = term)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray50") +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                 height = 0.2, linewidth = 0.8) +
  geom_point(size = 3, color = col_efficient) +
  labs(x = "Standardized Coefficient (β)",
       y = NULL) +
  manuscript_theme
```

```
## Warning: `geom_errobarh()` was deprecated in ggplot2 4.0.0.
## ℹ Please use the `orientation` argument of `geom_errorbar()` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.
```

```
## `height` was translated to `width`.
```

![Figure 5. Standardized regression coefficients (β) with 95% confidence intervals. Bars crossing zero indicate non-significant predictors at α = .05.](figure/coefficient-plot-1.png)


# Exploratory: Alternative RSVP Outcomes

As an exploratory extension, we examine whether HMM features also predict the attentional blink for other distractor conditions (Blink_ND, Blink_VD_Match, Blink_VD_Mismatch). If the HMM-captured suppression is specific to the consistent distractor color, we would expect stronger prediction of Blink_CD than of other blink measures.


``` r
outcomes <- c("Blink_CD", "Blink_ND", "Blink_VD_Match", "Blink_VD_Mismatch")
outcome_labels <- c(
  Blink_CD = "Consistent Distractor",
  Blink_ND = "No Distractor",
  Blink_VD_Match = "Variable (Match)",
  Blink_VD_Mismatch = "Variable (Mismatch)"
)

# Strongest bivariate predictor from the primary analysis
best_pred <- strongest$variable

exploratory_cors <- map_dfr(outcomes, function(outcome) {
  d <- transfer_data %>%
    select(all_of(outcome), all_of(best_pred)) %>%
    drop_na()

  ct <- cor.test(d[[best_pred]], d[[outcome]])

  tibble(
    Outcome = outcome_labels[outcome],
    Predictor = predictor_labels[best_pred],
    r = ct$estimate,
    p = ct$p.value,
    n = nrow(d)
  )
})

kable(exploratory_cors, digits = c(0, 0, 3, 4, 0),
      caption = sprintf("Table 6. Correlation between %s and each RSVP blink measure.",
                        predictor_labels[best_pred]))
```



Table: Table 6. Correlation between End-State P(Efficient) and each RSVP blink measure.

|Outcome               |Predictor              |      r|      p|  n|
|:---------------------|:----------------------|------:|------:|--:|
|Consistent Distractor |End-State P(Efficient) | -0.363| 0.0815| 24|
|No Distractor         |End-State P(Efficient) |  0.007| 0.9756| 24|
|Variable (Match)      |End-State P(Efficient) | -0.091| 0.6724| 24|
|Variable (Mismatch)   |End-State P(Efficient) | -0.212| 0.3204| 24|


# Summary


``` r
# Extract key statistics for the write-up
r2 <- summary(model_full)$r.squared
adj_r2 <- summary(model_full)$adj.r.squared
f_stat <- summary(model_full)$fstatistic
f_p <- pf(f_stat[1], f_stat[2], f_stat[3], lower.tail = FALSE)
```

The multiple regression testing whether HMM-derived features from the VST predict attentional blink magnitude for the consistent distractor color (Blink_CD) in the RSVP task yielded *R²* = 0.146 (adjusted *R²* = -0.242), *F*(5, 11) = 0.38, *p* = 0.8543.

The overall model did not reach significance, suggesting that the HMM-derived suppression learning features did not reliably predict attentional blink magnitude for the consistent distractor color in this sample. This null result may reflect several factors: the modest sample size (n = 24) limits power to detect moderate effects; the RSVP blink measure may capture processes partially distinct from the spatial suppression indexed by the HMM; or transfer of learned suppression may operate through mechanisms not fully captured by the five features extracted here. Nonetheless, the direction and magnitude of individual predictor effects remain informative for guiding future work with larger samples (Gaspelin & Luck, 2018a).

At the bivariate level, no individual predictor reached significance at p < .05. 2 predictor(s) showed trends (p < .10): Learning Slope, End-State P(Efficient). The strongest zero-order relationship was with End-State P(Efficient) (*r* = -0.363, *p* = 0.0815).


# References

Britton, M. K., & Anderson, B. A. (2020). Specificity and persistence of statistical learning in distractor suppression. *Journal of Experimental Psychology: Human Perception and Performance*, *46*(3), 324–334.

Feldmann-Wüstefeld, T., & Schubö, A. (2016). Intertrial priming due to distractor repetition is eliminated in homogeneous contexts. *Attention, Perception, & Psychophysics*, *78*(7), 1935–1947.

Gaspelin, N., & Luck, S. J. (2018a). Distinguishing among potential mechanisms of singleton suppression. *Journal of Experimental Psychology: Human Perception and Performance*, *44*(4), 626–644.

Won, B.-Y., & Leber, A. B. (2016). How do magnitude and frequency of monetary reward guide visual search? *Attention, Perception, & Psychophysics*, *78*(5), 1221–1231.
