<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 7: Extension of Portfolio 6</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
<li>
  <a href="p11.html">Portfolio 11</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 7: Extension of Portfolio 6</h1>

</div>


<blockquote>
<p>The projects should be numbered consecutively (i.e., in the order in
which you began them), and should include for each project a description
of the goal, the product (computer program, hand graph, computer graph,
etc.), the data, and some interpretation. Reports must be reproducible
and of high quality in terms of writing, grammar, presentation, etc.</p>
</blockquote>
<div id="extension-1-full-first-fixation-probability-decomposition"
class="section level2">
<h2>Extension 1: Full First-Fixation Probability Decomposition</h2>
<p>The main analysis of target fixation rate only examined the target
row of <code>firstfix2</code>. But understanding where the freed
probability mass goes as singleton fixation drops is theoretically
important. If suppression actively redirects attention toward the goal,
target fixation should rise as singleton fixation falls. If suppression
is purely inhibitory, i.e., reducing the singleton’s pull without
boosting target priority, target fixation should stay flat and the freed
probability should flow instead to nonsingleton items.</p>
<p>This extension plots and tests all three item types (Singleton,
Target, Nonsingleton per item) simultaneously across trials 1–3 in the
search task.</p>
<pre class="r"><code>rm(list = ls())
setwd(&quot;~/Documents/GitHub/DS4P_Portfolio&quot;)
library(&#39;NickPsych&#39;)
library(&#39;tidyverse&#39;)
library(&#39;reshape2&#39;)
library(&#39;writexl&#39;)
library(&#39;dplyr&#39;)
library(&#39;bruceR&#39;)
library(&#39;openxlsx&#39;)
library(&#39;knitr&#39;)
library(&#39;xtable&#39;)
library(&#39;patchwork&#39;)

# Load preprocessed data
accdata &lt;- read.csv(&quot;/Users/mumizz./Desktop/2025-2026/Courses/Data science for psych/Experiment3/Analysis Script/accdata.csv&quot;)

# Plot theme (matching manuscript style)
axis_text_size &lt;- 20
axis_tick_text_size &lt;- 18
graph_color &lt;- &quot;black&quot;
axis_tick_length &lt;- 0.25
axis_tick_units &lt;- &quot;cm&quot;
axis_thickness &lt;- 1

manuscript_theme &lt;- theme_classic() +
  theme(
    axis.line = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.title = element_text(size = axis_text_size),
    axis.text = element_text(colour = graph_color, size = axis_tick_text_size),
    axis.ticks = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.ticks.length.y = unit(axis_tick_length, axis_tick_units),
    axis.ticks.length.x = unit(axis_tick_length, axis_tick_units),
    legend.position = &quot;top&quot;,
    text = element_text(size = axis_tick_text_size)
  )</code></pre>
<pre class="r"><code># firstfix2 (identical to the original script)
accdata2 &lt;- subset(accdata, !is.na(SRT))

firstfix2 &lt;- as.data.frame(
  xtabs(~ curritem + subjnum + taskType + newtrial, data = accdata2)
)

# Total number of fixations on items in the display 
firstfix2$total &lt;- with(firstfix2, ave(Freq, interaction(subjnum, taskType, newtrial), FUN = sum))
# % of the toal each item was fixated 
firstfix2$perc &lt;- firstfix2$Freq / firstfix2$total

firstfix2$perc &lt;- with(firstfix2,
  ifelse(curritem == &#39;Nonsingleton&#39;, perc / 4, perc))
firstfix2$perc[is.nan(firstfix2$perc)] &lt;- 0
firstfix2 &lt;- firstfix2[, -c(5, 6)]</code></pre>
<pre class="r"><code># Descriptive table: all three item types 
decomp_desc &lt;- firstfix2 %&gt;%
  filter(taskType == &quot;search&quot;) %&gt;%
  group_by(curritem, newtrial) %&gt;%
  summarise(M  = round(mean(perc) * 100, 2),
            SD = round(sd(perc)  * 100, 2), .groups = &quot;drop&quot;)
kable(decomp_desc,
      caption = &quot;Table 4. First-fixation rate (%) by item type and trial position — search task only. Nonsingleton is a per-item rate (divided by 4). Chance = 16.67% for all three categories.&quot;)</code></pre>
<table>
<caption>Table 4. First-fixation rate (%) by item type and trial
position — search task only. Nonsingleton is a per-item rate (divided by
4). Chance = 16.67% for all three categories.</caption>
<thead>
<tr class="header">
<th align="left">curritem</th>
<th align="left">newtrial</th>
<th align="right">M</th>
<th align="right">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nonsingleton</td>
<td align="left">1</td>
<td align="right">11.39</td>
<td align="right">2.99</td>
</tr>
<tr class="even">
<td align="left">Nonsingleton</td>
<td align="left">2</td>
<td align="right">12.60</td>
<td align="right">3.20</td>
</tr>
<tr class="odd">
<td align="left">Nonsingleton</td>
<td align="left">3</td>
<td align="right">13.19</td>
<td align="right">3.44</td>
</tr>
<tr class="even">
<td align="left">Singleton</td>
<td align="left">1</td>
<td align="right">15.73</td>
<td align="right">5.06</td>
</tr>
<tr class="odd">
<td align="left">Singleton</td>
<td align="left">2</td>
<td align="right">9.90</td>
<td align="right">5.41</td>
</tr>
<tr class="even">
<td align="left">Singleton</td>
<td align="left">3</td>
<td align="right">8.29</td>
<td align="right">4.35</td>
</tr>
<tr class="odd">
<td align="left">Target</td>
<td align="left">1</td>
<td align="right">38.72</td>
<td align="right">14.79</td>
</tr>
<tr class="even">
<td align="left">Target</td>
<td align="left">2</td>
<td align="right">39.72</td>
<td align="right">16.42</td>
</tr>
<tr class="odd">
<td align="left">Target</td>
<td align="left">3</td>
<td align="right">38.97</td>
<td align="right">16.72</td>
</tr>
</tbody>
</table>
<p>To determine where the freed probability mass flows as singleton
capture decreases, we examined all three item types simultaneously
across trials 1–3 in the search task. Singleton fixation dropped
gradually from 15.73% (SD = 5.06%) on Trial 1, to 9.88% (SD = 5.41%) on
trial 2, then to 8.29% (SD = 4.35%) on trial 3.</p>
<pre class="r"><code>sing_fix &lt;- firstfix2 %&gt;% filter(taskType == &quot;search&quot;, curritem == &quot;Singleton&quot;)
MANOVA(data = sing_fix,
       subID = &quot;subjnum&quot;,
       dv = &quot;perc&quot;,
       within = &#39;newtrial&#39;,
       sph.correction = &quot;GG&quot;,
       digits = 3) %&gt;%
  EMMEANS(&#39;newtrial&#39;)</code></pre>
<pre><code>## 
##     * Data are aggregated to mean (across items/trials)
##     if there are &gt;=2 observations per subject and cell.
##     You may use Linear Mixed Model to analyze the data,
##     e.g., with subjects and items as level-2 clusters.</code></pre>
<pre><code>## 
## ====== ANOVA (Within-Subjects Design) ======
## 
## Descriptives:
## ────────────────────────────
##  &quot;newtrial&quot;  Mean    S.D.  n
## ────────────────────────────
##   newtrial1 0.157 (0.051) 40
##   newtrial2 0.099 (0.054) 40
##   newtrial3 0.083 (0.043) 40
## ────────────────────────────
## Total sample size: N = 40
## 
## ANOVA Table:
## Dependent variable(s):      perc
## Between-subjects factor(s): –
## Within-subjects factor(s):  newtrial
## Covariate(s):               –
## ────────────────────────────────────────────────────────────────────────────
##              MS   MSE   df1    df2      F     p     η²p [90% CI of η²p]  η²G
## ────────────────────────────────────────────────────────────────────────────
## newtrial  0.072 0.001 1.694 66.049 50.382 &lt;.001 ***   .564 [.430, .659] .299
## ────────────────────────────────────────────────────────────────────────────
## Sphericity correction method: GG (Greenhouse-Geisser)
## MSE = mean square error (the residual variance of the linear model)
## η²p = partial eta-squared = SS / (SS + SSE) = F * df1 / (F * df1 + df2)
## ω²p = partial omega-squared = (F - 1) * df1 / (F * df1 + df2 + 1)
## η²G = generalized eta-squared (see Olejnik &amp; Algina, 2003)
## Cohen’s f² = η²p / (1 - η²p)
## 
## Levene’s Test for Homogeneity of Variance:
## No between-subjects factors. No need to do the Levene’s test.
## 
## Mauchly’s Test of Sphericity:
## ───────────────────────────────
##           Mauchly&#39;s W     p    
## ───────────────────────────────
## newtrial       0.8191  .023 *  
## ───────────────────────────────
## 
## ------ EMMEANS (effect = &quot;newtrial&quot;) ------
## 
## Joint Tests of &quot;newtrial&quot;:
## ──────────────────────────────────────────────────────
##    Effect df1 df2      F     p     η²p [90% CI of η²p]
## ──────────────────────────────────────────────────────
##  newtrial   2  39 57.665 &lt;.001 ***   .747 [.624, .818]
## ──────────────────────────────────────────────────────
## Note. Simple effects of repeated measures with 3 or more levels
## are different from the results obtained with SPSS MANOVA syntax.
## 
## Estimated Marginal Means of &quot;newtrial&quot;:
## ─────────────────────────────────────────
##  &quot;newtrial&quot; Mean [95% CI of Mean]    S.E.
## ─────────────────────────────────────────
##   newtrial1  0.157 [0.141, 0.174] (0.008)
##   newtrial2  0.099 [0.082, 0.116] (0.009)
##   newtrial3  0.083 [0.069, 0.097] (0.007)
## ─────────────────────────────────────────
## 
## Pairwise Comparisons of &quot;newtrial&quot;:
## ────────────────────────────────────────────────────────────────────────────────────
##               Contrast Estimate    S.E. df       t     p     Cohen’s d [95% CI of d]
## ────────────────────────────────────────────────────────────────────────────────────
##  newtrial2 - newtrial1   -0.058 (0.009) 39  -6.264 &lt;.001 *** -1.182 [-1.655, -0.710]
##  newtrial3 - newtrial1   -0.074 (0.007) 39 -10.656 &lt;.001 *** -1.508 [-1.862, -1.154]
##  newtrial3 - newtrial2   -0.016 (0.007) 39  -2.342  .073 .   -0.326 [-0.674,  0.022]
## ────────────────────────────────────────────────────────────────────────────────────
## Pooled SD for computing Cohen’s d: 0.049
## P-value adjustment: Bonferroni method for 3 tests.
## 
## Disclaimer:
## By default, pooled SD is Root Mean Square Error (RMSE).
## There is much disagreement on how to compute Cohen’s d.
## You are completely responsible for setting `sd.pooled`.
## You might also use `effectsize::t_to_d()` to compute d.</code></pre>
<p>A one-way within-subjects ANOVA confirmed a significant effect of
trial position on singleton fixation rate, F(1.69, 66.05) = 50.38, p
&lt; .001, η²p = .56 (Greenhouse-Geisser corrected; Mauchly’s W = 0.819,
p = .023). Both contrasts against trial 1 were highly significant after
Bonferroni correction, (1) trial 2 vs. trial 1, Mdiff = -5.85%, t(39) =
-6.26, p &lt; .001, Cohen’s d = -1.18, (2) trial 3 vs. trial 1, Mdiff =
-7.44%, t(39) = -10.66, p &lt; .001, Cohen’s d = -1.51. The trial 3
vs. trial 2 contrast was marginal after Bonferroni correction (t(39) =
-2.34, p = .073, Cohen’s d = -.33), suggesting that the bulk of
suppression development occurs on the first same-color repetition.</p>
<pre class="r"><code>decomp_summary &lt;- with(
  firstfix2 %&gt;%
    filter(taskType == &quot;search&quot;) %&gt;%
    mutate(group_label = paste(curritem, newtrial)),
  cmErrBar(perc, subjnum, group_label, &quot;ci&quot;)
) %&gt;%
  separate(group, into = c(&quot;item&quot;, &quot;trial&quot;), sep = &quot; &quot;) %&gt;%
  mutate(trial = factor(trial, levels = c(&quot;1&quot;, &quot;2&quot;, &quot;3&quot;)),
         item = factor(item, levels = c(&quot;Singleton&quot;, &quot;Target&quot;, &quot;Nonsingleton&quot;)))

ggplot(decomp_summary,
       aes(x = trial, y = mean * 100, group = item,
           color = item, linetype = item, shape = item)) +
  geom_errorbar(aes(ymin = minus * 100, ymax = plus * 100),
                width = 0.15, linewidth = 1.1) +
  geom_line(linewidth = 1.1) +
  geom_point(size = 4) +
  geom_hline(yintercept = 100 / 6, linetype = &quot;dashed&quot;,
             color = &quot;gray50&quot;, linewidth = 0.8) +
  annotate(&quot;text&quot;, x = 0.6, y = 100 / 6 + 1.5,
           label = &quot;chance (1/6)&quot;, color = &quot;gray50&quot;, size = 4.5, hjust = 0) +
  scale_color_manual(
    values = c(&quot;Singleton&quot; = &quot;#E74C3C&quot;, &quot;Target&quot; = &quot;#333333&quot;, &quot;Nonsingleton&quot; = &quot;#95A5A6&quot;),
    labels = c(&quot;Singleton&quot;, &quot;Target&quot;, &quot;Nonsingleton (per item)&quot;)) +
  scale_shape_manual(
    values = c(&quot;Singleton&quot; = 15, &quot;Target&quot; = 16, &quot;Nonsingleton&quot; = 17),
    labels = c(&quot;Singleton&quot;, &quot;Target&quot;, &quot;Nonsingleton (per item)&quot;)) +
  scale_linetype_manual(
    values = c(&quot;Singleton&quot; = &quot;dashed&quot;, &quot;Target&quot; = &quot;solid&quot;, &quot;Nonsingleton&quot; = &quot;dotted&quot;),
    labels = c(&quot;Singleton&quot;, &quot;Target&quot;, &quot;Nonsingleton (per item)&quot;)) +
  labs(x = &quot;Trials with Same Color&quot;,
       y = &quot;First-Fixation Rate (%)&quot;,
       color = &quot;Item Type&quot;,
       shape = &quot;Item Type&quot;,
       linetype = &quot;Item Type&quot;) +
  manuscript_theme</code></pre>
<div class="figure">
<img src="p07_files/figure-html/decomp-plot-1.png" alt="Figure S4. First-fixation rate (%) for each item type across trial positions in the search task. Chance baseline = 16.67% (dashed line). Error bars = 95% CI (Cousineau-Morey corrected)." width="768" />
<p class="caption">
Figure S4. First-fixation rate (%) for each item type across trial
positions in the search task. Chance baseline = 16.67% (dashed line).
Error bars = 95% CI (Cousineau-Morey corrected).
</p>
</div>
<p>The figure showed the first fixation rate for all three item types
across the 3-trial same-color sequence in the search task. The target
line sit flat approximately 39 throughout, well above the 16.67% chance
baseline, indicating that target guidance is strong and entirely
unaffected by the learning cycle. The singleton line told the opposite
trend: it started near the chance at 15% on trial 1, then drops sharply
to about 10% on trial 2 and falls further down to about 8% on trial 3,
largely below chance by the end of the sequence. The nonsingleton line
lay in at about 12% at trial 1 and drifts upward toward the chance line
by trial 3.</p>
<p>Critically, the relationship between all three lines together might
suggest: as the singleton line falls by approximately 8 percentage
points across trials, the freed probability mass does not flow toward
the target, i.e., remaining flat, but instead disperses to the
nonsingleton items. This pattern is the hallmark of a purely inhibitory
suppression process: the oculomotor system learns to remove the
singleton’s attentional priority without actively redirecting attention
toward the goal, such that the beneficiaries of suppression are random
non-target locations rather than the item participants are actually
searching for.</p>
</div>
<div
id="extension-2-individual-differences-does-t1-capture-predict-learning"
class="section level2">
<h2>Extension 2: Individual Differences — Does T1 Capture Predict
Learning?</h2>
<p>If being overtly captured by the singleton on trial 1 is what drives
suppression learning, then participants who showed stronger T1 capture
should show stronger T2/T3 suppression. This extension tests that
prediction directly at the individual level using Pearson correlations
between each participant’s T1 singleton fixation rate and their
subsequent learning magnitude (T1−T3 reduction in singleton
fixation).</p>
<pre class="r"><code># Per-participant singleton fixation rate in search task, wide format
sing_wide &lt;- firstfix2 %&gt;%
  filter(taskType == &quot;search&quot;, curritem == &quot;Singleton&quot;) %&gt;%
  pivot_wider(names_from = newtrial, values_from = perc) %&gt;%
  rename(t1 = `1`, t2 = `2`, t3 = `3`)

# Learning magnitude = reduction in singleton fixation from T1 to T3
sing_wide$learning_t1_t3 &lt;- sing_wide$t1 - sing_wide$t3

# Individual Differences: T1 Capture and Learning
# Correlation: T1 singleton rate vs. T3 singleton rate
cor1 &lt;- cor.test(sing_wide$t1, sing_wide$t3, method = &quot;pearson&quot;)
print(cor1)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sing_wide$t1 and sing_wide$t3
## t = 4.2548, df = 38, p-value = 0.0001317
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3116886 0.7473154
## sample estimates:
##       cor 
## 0.5680443</code></pre>
<pre class="r"><code># Correlation: T1 singleton rate vs. learning magnitude (T1 − T3) 
cor2 &lt;- cor.test(sing_wide$t1, sing_wide$learning_t1_t3, method = &quot;pearson&quot;)
print(cor2)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sing_wide$t1 and sing_wide$learning_t1_t3
## t = 4.4635, df = 38, p-value = 6.98e-05
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3364364 0.7592749
## sample estimates:
##       cor 
## 0.5864808</code></pre>
<pre class="r"><code># T1 singleton rate vs. T2 singleton rate
cor3 &lt;- cor.test(sing_wide$t1, sing_wide$t2, method = &quot;pearson&quot;)
print(cor3)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  sing_wide$t1 and sing_wide$t2
## t = 2.4365, df = 38, p-value = 0.01963
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.06332575 0.60932232
## sample estimates:
##       cor 
## 0.3675839</code></pre>
<p>Three Pearson’s correlation analyses were conducted to examine
whether individual difference in initial capture predicted subsequent
learning. First, trial 1 singleton fixation rate was positively
correlated with trial 3 singleton fixation rate, r = .57, t(38) = 4.25,
p &lt; .001, 95% CI[.31, .75], indicating that participants who were
more strongly captured on Trial 1 still showed higher singleton fixation
on trial 3 than others. Second, and more directly, trial 1 capture rate
was positively correlated with learning magnitude (T1−T3 reduction), r =
.59, t(38) = 4.46, p &lt; .001, 95% CI[.34, .76], confirming that
participants who experienced stronger initial capture showed greater
suppression by Trial 3. This correlation allowed us to infer that high
initial capture rate is associated with a larger learning rate within
subjects. Furthermore, this relationship was detected by the 3rd
correlation analysis: Trial 1 capture rate predicted Trial 2 singleton
fixation rate, r = .37, t(38) = 2.44, p = .020, 95% CI[.06, .61],
indicating that the learning advantage of high-capture individuals
emerges as early as the first same-color repetition. Together, these
correlations provide individual-level evidence for the capture-learning
mechanism: the more strongly the oculomotor system was initially drawn
to the singleton, the more forcefully it learned to suppress it,
consistent with the interpretation that overt capture is not merely a
correlate of the learning process but its primary driver.</p>
<pre class="r"><code>ggplot(sing_wide, aes(x = t1 * 100, y = learning_t1_t3 * 100)) +
  geom_point(size = 3, color = &quot;gray35&quot;, alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;, se = TRUE,
              color = &quot;black&quot;, fill = &quot;gray80&quot;, linewidth = 1.1) +
  annotate(&quot;text&quot;,
           x = max(sing_wide$t1 * 100) - 1,
           y = max(sing_wide$learning_t1_t3 * 100) - 1,
           label = &quot;r = .59, p &lt; .001&quot;,
           hjust = 1, size = 5.5) +
  labs(x = &quot;Trial 1 Singleton Fixation Rate&quot;,
       y = &quot;Learning Magnitude\n(T1-T3 Singleton Fixation Rate&quot;) +
  manuscript_theme</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="figure">
<img src="p07_files/figure-html/ind-diff-plot-1.png" alt="Figure S5. Scatter plot of Trial 1 singleton fixation rate vs. learning magnitude (Trial 1 − Trial 3 reduction). Each point = one participant. Line = OLS regression with 95% CI shading." width="672" />
<p class="caption">
Figure S5. Scatter plot of Trial 1 singleton fixation rate vs. learning
magnitude (Trial 1 − Trial 3 reduction). Each point = one participant.
Line = OLS regression with 95% CI shading.
</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
