<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 9 : Within-Trial Eye Movement Sequence</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 9 : Within-Trial Eye Movement
Sequence</h1>

</div>


<blockquote>
<p>The projects should be numbered consecutively (i.e., in the order in
which you began them), and should include for each project a description
of the goal, the product (computer program, hand graph, computer graph,
etc.), the data, and some interpretation. Reports must be reproducible
and of high quality in terms of writing, grammar, presentation, etc.</p>
</blockquote>
<div id="background" class="section level1">
<h1>Background</h1>
<p>The last two portfolios established that target first-fixation rate
is robustly above chance throughout the three-trial suppression learning
sequence but completely unmodulated by it. Singleton capture falls
sharply from trials 1 to 3; target fixation rate does not rise. This may
suggest that suppression is purely inhibitory - it removes the
singleton’s oculomotor priority without redistributing attention toward
the goal.</p>
<p>But the analyses so far have looked at only one moment in each trial
- the very first fixation. A full trial contains an entire sequence of
eye movements as the participant scans the display, gets captured,
recovers, and eventually finds the target. Two questions that no prior
analysis can answer:</p>
<ul>
<li><p>First, when the eye is captured by the singleton distractor, does
suppression learning help participants escape more efficiently? If
participants on trial 3 are better at immediately redirecting to the
target after being trapped (compared to trial 1), that would suggest
suppression reshapes not just whether capture happens, but the recovery
dynamics that follow. Conversely, if post-capture recovery is constant
across trial positions, it means suppression acts only at the initial
decision stage, with no downstream influence once the eye has already
landed on the wrong item.</p></li>
<li><p>Second, does suppression learning make the overall search path
more efficient? Fewer fixations needed to reach the target would
indicate that deprioritizing the singleton streamlines the entire scan
sequence. A flat result would suggest that the search process after the
first saccade unfolds identically regardless of whether the participant
is on trial 1 (unsuppressed) or trial 3 (fully suppressed).</p></li>
</ul>
<p>Together, these two questions test where in the oculomotor hierarchy
suppression learning operates. If both are null (post-capture recovery
unchanged, fixation count to target unchanged), the conclusion is a
sharp mechanistic one: suppression learning is exclusively a
pre-saccadic phenomenon, operating during the initial motor planning
period while the eye is still at the central fixation point. Once the
eye leaves centre, everything that follows is identical across the
learning arc. The mechanism does not make search smarter or faster; it
simply prevents misdirection at the very first step. In this way, it is
reasonable to infer that what participants learn in the process of
distractor suppression is - more prepared (or more ready) to move their
eyes for the first search.</p>
</div>
<div id="goals" class="section level1">
<h1>Goals</h1>
<p>This portfolio examines the full within-trial fixation sequence in
the search task to test whether suppression learning reshapes eye
movement behavior beyond the first saccade. Two specific goals are
pursued:</p>
<ul>
<li><p><em>Post-capture recovery</em>: On trials where the first
fixation is captured by the singleton, does the probability of
immediately redirecting the eye to the target on the next fixation
increase across Trials 1 to 3? If so, suppression learning improves not
just capture avoidance but also recovery efficiency once captured. If
not, recovery behaviour is independent of suppression state.</p></li>
<li><p><em>Search efficiency</em>: Does the number of fixations required
to reach the target decrease across Trials 1 to 3? If suppression
learning streamlines the overall scan path, participants should reach
the target more directly on Trial 3 than on Trial 1. If the fixation
count is flat, the benefit of suppression is confined entirely to the
first saccade.</p></li>
</ul>
</div>
<div id="analysis" class="section level1">
<h1>Analysis</h1>
<div id="setup" class="section level2">
<h2>Setup</h2>
<pre class="r"><code># Identical to previous portfolio 
rm(list = ls())
setwd(&quot;~/Documents/GitHub/DS4P_Portfolio&quot;)
library(&#39;NickPsych&#39;)
library(&#39;tidyverse&#39;)
library(&#39;reshape2&#39;)
library(&#39;writexl&#39;)
library(&#39;dplyr&#39;)
library(&#39;bruceR&#39;)
library(&#39;openxlsx&#39;)
library(&#39;knitr&#39;)
library(&#39;xtable&#39;)
library(&#39;patchwork&#39;)

# Load preprocessed data
accdata &lt;- read.csv(&quot;/Users/mumizz./Desktop/2025-2026/Courses/Data science for psych/Experiment3/Analysis Script/accdata.csv&quot;)

trimdata &lt;- read.csv(&quot;/Users/mumizz./Desktop/2025-2026/Courses/Data science for psych/Experiment3/Analysis Script/trimdata.csv&quot;)

# Plot theme (matching manuscript style)
axis_text_size &lt;- 20
axis_tick_text_size &lt;- 18
graph_color &lt;- &quot;black&quot;
axis_tick_length &lt;- 0.25
axis_tick_units &lt;- &quot;cm&quot;
axis_thickness &lt;- 1

manuscript_theme &lt;- theme_classic() +
  theme(
    axis.line = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.title = element_text(size = axis_text_size),
    axis.text = element_text(colour = graph_color, size = axis_tick_text_size),
    axis.ticks = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.ticks.length.y = unit(axis_tick_length, axis_tick_units),
    axis.ticks.length.x = unit(axis_tick_length, axis_tick_units),
    legend.position = &quot;top&quot;,
    text = element_text(size = axis_tick_text_size)
  )</code></pre>
</div>
<div id="data-preparation" class="section level2">
<h2>Data preparation</h2>
<p>To address these questions we need the full fixation sequence per
trial. The variable <code>search_full</code> is constructed from
<code>trimdata</code> retaining all saccade indices (saccindex 0–10),
filtered to good formal search trials for included subjects - the same
population as all prior analyses, but with the saccindex == 1
restriction lifted.</p>
<pre class="r"><code># Create Search_full
subj &lt;- unique(accdata$subjnum)

search_full &lt;- trimdata %&gt;% 
  filter(subjnum %in% subj,
         phase != &quot;practice&quot;,
         ACC == 1,
         keepRT == 1,
         brokeFixation != 1,
         searchArray == &quot;search&quot;) %&gt;%
  mutate(newtrial = ((trial - 121) %% 3) + 1,
         trial_group = (trial - 121) %/% 3)

summary(search_full)</code></pre>
<pre><code>##  CURRENT_FIX_DURATION CURRENT_FIX_INDEX CURRENT_FIX_X    CURRENT_FIX_Y   
##  Min.   :   2         Min.   : 1.000    Min.   : 361.8   Min.   :  -3.6  
##  1st Qu.: 140         1st Qu.: 1.000    1st Qu.: 895.9   1st Qu.: 423.0  
##  Median : 186         Median : 2.000    Median : 957.1   Median : 537.3  
##  Mean   : 218         Mean   : 2.669    Mean   : 955.7   Mean   : 542.6  
##  3rd Qu.: 265         3rd Qu.: 4.000    3rd Qu.:1016.9   3rd Qu.: 668.5  
##  Max.   :1632         Max.   :11.000    Max.   :1623.4   Max.   :1934.3  
##                                                                          
##  PREVIOUS_SAC_START_TIME      ACC       L1_ID              L1_col         
##  Min.   :-125.0          Min.   :1   Length:47350       Length:47350      
##  1st Qu.: 226.0          1st Qu.:1   Class :character   Class :character  
##  Median : 378.0          Median :1   Mode  :character   Mode  :character  
##  Mean   : 445.9          Mean   :1                                        
##  3rd Qu.: 588.0          3rd Qu.:1                                        
##  Max.   :1873.0          Max.   :1                                        
##  NA&#39;s   :12063                                                            
##    L1_shape            L2_ID              L2_col            L2_shape        
##  Length:47350       Length:47350       Length:47350       Length:47350      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##     L3_ID              L3_col            L3_shape            L4_ID          
##  Length:47350       Length:47350       Length:47350       Length:47350      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##     L4_col            L4_shape            L5_ID              L5_col         
##  Length:47350       Length:47350       Length:47350       Length:47350      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##    L5_shape            L6_ID              L6_col            L6_shape        
##  Length:47350       Length:47350       Length:47350       Length:47350      
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##                                                                             
##                                                                             
##                                                                             
##                                                                             
##    LetterID               RT           Resp                age       
##  Length:47350       Min.   : 231   Length:47350       Min.   :18.00  
##  Class :character   1st Qu.: 754   Class :character   1st Qu.:18.00  
##  Mode  :character   Median : 930   Mode  :character   Median :20.00  
##                     Mean   :1005                      Mean   :21.81  
##                     3rd Qu.:1192                      3rd Qu.:25.00  
##                     Max.   :2000                      Max.   :31.00  
##                                                                      
##      block       brokeFixation   expVers             gender         
##  Min.   : 3.00   Min.   :-1    Length:47350       Length:47350      
##  1st Qu.: 4.00   1st Qu.:-1    Class :character   Class :character  
##  Median : 6.00   Median :-1    Mode  :character   Mode  :character  
##  Mean   : 6.41   Mean   :-1                                         
##  3rd Qu.: 8.00   3rd Qu.:-1                                         
##  Max.   :10.00   Max.   :-1                                         
##                                                                     
##      hand           searchArray          singAngle     singCol         
##  Length:47350       Length:47350       Min.   :  0   Length:47350      
##  Class :character   Class :character   1st Qu.: 60   Class :character  
##  Mode  :character   Mode  :character   Median :120   Mode  :character  
##                                        Mean   :147                     
##                                        3rd Qu.:240                     
##                                        Max.   :300                     
##                                                                        
##     singLoc     singTargAngle      subjnum        targAngle    
##  Min.   :1.00   Min.   : 60.0   Min.   :101.0   Min.   :  0.0  
##  1st Qu.:2.00   1st Qu.: 60.0   1st Qu.:112.0   1st Qu.: 60.0  
##  Median :3.00   Median :120.0   Median :122.0   Median :180.0  
##  Mean   :3.45   Mean   :108.6   Mean   :121.6   Mean   :152.6  
##  3rd Qu.:5.00   3rd Qu.:120.0   3rd Qu.:131.0   3rd Qu.:240.0  
##  Max.   :6.00   Max.   :180.0   Max.   :142.0   Max.   :300.0  
##                                                                
##    targCol             targID           targLetter           targLoc     
##  Length:47350       Length:47350       Length:47350       Min.   :1.000  
##  Class :character   Class :character   Class :character   1st Qu.:2.000  
##  Mode  :character   Mode  :character   Mode  :character   Median :4.000  
##                                                           Mean   :3.544  
##                                                           3rd Qu.:5.000  
##                                                           Max.   :6.000  
##                                                                          
##   targShape           taskType             trial            SRT        
##  Length:47350       Length:47350       Min.   :121.0   Min.   :-132.0  
##  Class :character   Class :character   1st Qu.:233.0   1st Qu.: 219.0  
##  Mode  :character   Mode  :character   Median :351.0   Median : 371.0  
##                                        Mean   :355.1   Mean   : 438.9  
##                                        3rd Qu.:477.0   3rd Qu.: 581.0  
##                                        Max.   :600.0   Max.   :1866.0  
##                                                        NA&#39;s   :12063   
##      Dwell         phase              currloc       curritem        
##  Min.   :   2   Length:47350       Min.   :1.00   Length:47350      
##  1st Qu.: 140   Class :character   1st Qu.:2.00   Class :character  
##  Median : 186   Mode  :character   Median :4.00   Mode  :character  
##  Mean   : 218                      Mean   :3.47                     
##  3rd Qu.: 265                      3rd Qu.:5.00                     
##  Max.   :1632                      Max.   :6.00                     
##                                    NA&#39;s   :2                        
##    saccindex          numfix           normX            normY       
##  Min.   : 0.000   Min.   : 0.000   Min.   : 348.2   Min.   :-671.3  
##  1st Qu.: 0.000   1st Qu.: 2.000   1st Qu.: 926.5   1st Qu.: 280.7  
##  Median : 1.000   Median : 3.000   Median : 959.8   Median : 433.7  
##  Mean   : 1.631   Mean   : 3.284   Mean   : 958.2   Mean   : 437.9  
##  3rd Qu.: 2.000   3rd Qu.: 4.000   3rd Qu.: 991.7   3rd Qu.: 555.7  
##  Max.   :10.000   Max.   :10.000   Max.   :2108.1   Max.   :1340.0  
##                                                                     
##   normcurrloc        keepRT    goodTrials    newtrial      trial_group   
##  Min.   :1.000   Min.   :1   Min.   :1    Min.   :1.000   Min.   :  0.0  
##  1st Qu.:1.000   1st Qu.:1   1st Qu.:1    1st Qu.:2.000   1st Qu.: 37.0  
##  Median :2.000   Median :1   Median :1    Median :3.000   Median : 76.0  
##  Mean   :2.588   Mean   :1   Mean   :1    Mean   :2.258   Mean   : 77.6  
##  3rd Qu.:4.000   3rd Qu.:1   3rd Qu.:1    3rd Qu.:3.000   3rd Qu.:118.0  
##  Max.   :6.000   Max.   :1   Max.   :1    Max.   :3.000   Max.   :159.0  
## </code></pre>
</div>
<div id="part-1---post-capture-saccade" class="section level2">
<h2>Part 1 - Post-capture Saccade</h2>
<pre class="r"><code># Build captured-trial dataset and identify post-capture destination 

## saccindex 1 = first fixation; saccindex 2 = second
s1 &lt;- search_full %&gt;%
  filter(saccindex == 1) %&gt;%
  select(subjnum, trial, newtrial, s1_item = curritem)

s2 &lt;- search_full %&gt;%
  filter(saccindex == 2) %&gt;%
  select(subjnum, trial, s2_item = curritem)

## Keep only captured trials (s1 = Singleton) that also have a second fixation
post_cap &lt;- s1 %&gt;%
  left_join(s2, by = c(&quot;subjnum&quot;, &quot;trial&quot;)) %&gt;%
  filter(s1_item == &quot;Singleton&quot;, !is.na(s2_item)) %&gt;%
  mutate(s2_target = as.integer(s2_item == &quot;Target&quot;),
         s2_nonsingleton = as.integer(s2_item == &quot;Nonsingleton&quot;),
         s2_singleton = as.integer(s2_item == &quot;Singleton&quot;),
         newtrial = factor(newtrial))

## Overall 
post_cap %&gt;%
  summarise(P_target = round(mean(s2_target)       * 100, 2),
            P_nonsingleton = round(mean(s2_nonsingleton)  * 100, 2),
            P_singleton_again = round(mean(s2_singleton)     * 100, 2),
            n = n()) %&gt;%
  kable(caption = &quot;Table 5. Post-capture saccade destination (% of captured trials)&quot;)</code></pre>
<table>
<caption>Table 5. Post-capture saccade destination (% of captured
trials)</caption>
<thead>
<tr class="header">
<th align="right">P_target</th>
<th align="right">P_nonsingleton</th>
<th align="right">P_singleton_again</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">52.14</td>
<td align="right">41.56</td>
<td align="right">6.3</td>
<td align="right">1381</td>
</tr>
</tbody>
</table>
<pre class="r"><code>## By newtrial
post_cap %&gt;%
  group_by(newtrial) %&gt;%
  summarise(P_target = round(mean(s2_target)       * 100, 2),
            P_nonsingleton = round(mean(s2_nonsingleton)  * 100, 2),
            P_singleton_again = round(mean(s2_singleton)     * 100, 2),
            n = n(), .groups = &quot;drop&quot;) %&gt;%
  kable(caption = &quot;Table 6. Post-capture destination by trial position.&quot;)</code></pre>
<table>
<caption>Table 6. Post-capture destination by trial position.</caption>
<thead>
<tr class="header">
<th align="left">newtrial</th>
<th align="right">P_target</th>
<th align="right">P_nonsingleton</th>
<th align="right">P_singleton_again</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">56.57</td>
<td align="right">36.02</td>
<td align="right">7.42</td>
<td align="right">472</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">49.67</td>
<td align="right">46.03</td>
<td align="right">4.30</td>
<td align="right">302</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="right">49.92</td>
<td align="right">43.66</td>
<td align="right">6.43</td>
<td align="right">607</td>
</tr>
</tbody>
</table>
<p>On trials where the first fixation landed on the singleton, we
examined where the eye moved next (i.e., the second fixation). Across
all participants and trial positions, 1,381 such capture trials were
identified. Overall, the second fixation went to the target on 52.14% of
these trials, to a nonsingleton on 41.56%, and back to the singleton on
6.30%. Broken down by trial position, P(S2 = Target | S1 = Singleton)
was 56.57% on trial 1, 49.67% on trial 2, and 49.92% on trial 3.</p>
<pre class="r"><code># ANOVA on P(s2 = Target | captured) - Given the eye was just captured, where does it go next?
pct_subj &lt;- post_cap %&gt;%
  group_by(subjnum, newtrial) %&gt;%
  summarise(p_target = mean(s2_target), .groups = &quot;drop&quot;)

MANOVA(data = pct_subj,
       subID = &quot;subjnum&quot;,
       dv = &quot;p_target&quot;,
       within = &quot;newtrial&quot;,
       sph.correction = &quot;GG&quot;,
       digits = 2) %&gt;%
  EMMEANS(&quot;newtrial&quot;)</code></pre>
<pre><code>## 
##     * Data are aggregated to mean (across items/trials)
##     if there are &gt;=2 observations per subject and cell.
##     You may use Linear Mixed Model to analyze the data,
##     e.g., with subjects and items as level-2 clusters.</code></pre>
<pre><code>## Warning: Missing values for 1 ID(s), which were removed before analysis:
## 135
## Below the first few rows (in wide format) of the removed cases with missing data.
##      subjnum newtrial1 newtrial2 newtrial3
## # 33     135       0.8       NaN 0.8333333</code></pre>
<pre><code>## 
## ====== ANOVA (Within-Subjects Design) ======
## 
## Descriptives:
## ──────────────────────────
##  &quot;newtrial&quot; Mean   S.D.  n
## ──────────────────────────
##   newtrial1 0.57 (0.22) 39
##   newtrial2 0.52 (0.22) 39
##   newtrial3 0.52 (0.19) 39
## ──────────────────────────
## Total sample size: N = 40
## 
## ANOVA Table:
## Dependent variable(s):      p_target
## Between-subjects factor(s): –
## Within-subjects factor(s):  newtrial
## Covariate(s):               –
## ─────────────────────────────────────────────────────────────────────
##             MS  MSE  df1   df2    F     p     η²p [90% CI of η²p] η²G
## ─────────────────────────────────────────────────────────────────────
## newtrial  0.03 0.03 1.89 71.86 1.07  .344          .03 [.00, .10] .01
## ─────────────────────────────────────────────────────────────────────
## Sphericity correction method: GG (Greenhouse-Geisser)
## MSE = mean square error (the residual variance of the linear model)
## η²p = partial eta-squared = SS / (SS + SSE) = F * df1 / (F * df1 + df2)
## ω²p = partial omega-squared = (F - 1) * df1 / (F * df1 + df2 + 1)
## η²G = generalized eta-squared (see Olejnik &amp; Algina, 2003)
## Cohen’s f² = η²p / (1 - η²p)
## 
## Levene’s Test for Homogeneity of Variance:
## No between-subjects factors. No need to do the Levene’s test.
## 
## Mauchly’s Test of Sphericity:
## ───────────────────────────────
##           Mauchly&#39;s W     p    
## ───────────────────────────────
## newtrial       0.9424  .334    
## ───────────────────────────────
## 
## ------ EMMEANS (effect = &quot;newtrial&quot;) ------
## 
## Joint Tests of &quot;newtrial&quot;:
## ─────────────────────────────────────────────────────
##    Effect df1 df2     F     p     η²p [90% CI of η²p]
## ─────────────────────────────────────────────────────
##  newtrial   2  38 0.884  .422       .044 [.000, .162]
## ─────────────────────────────────────────────────────
## Note. Simple effects of repeated measures with 3 or more levels
## are different from the results obtained with SPSS MANOVA syntax.
## 
## Estimated Marginal Means of &quot;newtrial&quot;:
## ─────────────────────────────────────────
##  &quot;newtrial&quot; Mean [95% CI of Mean]    S.E.
## ─────────────────────────────────────────
##   newtrial1  0.566 [0.493, 0.638] (0.036)
##   newtrial2  0.517 [0.447, 0.587] (0.035)
##   newtrial3  0.524 [0.461, 0.587] (0.031)
## ─────────────────────────────────────────
## 
## Pairwise Comparisons of &quot;newtrial&quot;:
## ───────────────────────────────────────────────────────────────────────────────────
##               Contrast Estimate    S.E. df      t     p     Cohen’s d [95% CI of d]
## ───────────────────────────────────────────────────────────────────────────────────
##  newtrial2 - newtrial1   -0.048 (0.037) 38 -1.292  .612      -0.217 [-0.637, 0.203]
##  newtrial3 - newtrial1   -0.041 (0.038) 38 -1.088  .851      -0.186 [-0.614, 0.242]
##  newtrial3 - newtrial2    0.007 (0.031) 38  0.220 1.000       0.031 [-0.319, 0.381]
## ───────────────────────────────────────────────────────────────────────────────────
## Pooled SD for computing Cohen’s d: 0.223
## P-value adjustment: Bonferroni method for 3 tests.
## 
## Disclaimer:
## By default, pooled SD is Root Mean Square Error (RMSE).
## There is much disagreement on how to compute Cohen’s d.
## You are completely responsible for setting `sd.pooled`.
## You might also use `effectsize::t_to_d()` to compute d.</code></pre>
<p>A one-way within-subjects ANOVA on subject-level P(S2 = Target |
captured) revealed no significant effect of trial position, F(1.89,
71.86) = 1.07, p = .34, η²p = .027. All pairwise contrasts were
non-significant after Bonferroni correction. Post-capture recovery
behaviour (the probability of immediately redirecting to the target
after being trapped by the singleton) was entirely stable across the
three-trial learning arc.</p>
<div id="markov-transition-matrix" class="section level3">
<h3>Markov Transition Matrix</h3>
<p>Beyond the first capture, the full scan path can be described as a
Markov chain of item-to-item transitions. This quantifies the complete
search dynamics, not just what happens after saccindex 1, but at any
point in the sequence. In other words, it treats the entire fixation
sequence as a chain of transitions and computes the probability of
moving from one item type to every item type, regardless of when in the
trial that transition happens.</p>
<pre class="r"><code>pairs &lt;- search_full %&gt;%
  arrange(subjnum, trial, saccindex) %&gt;%
  group_by(subjnum, trial) %&gt;%
  mutate(next_item = lead(curritem)) %&gt;%
  filter(!is.na(curritem), !is.na(next_item)) %&gt;%
  ungroup()

# Full Markov Transition Matrix (all trials pooled)
pairs %&gt;%
  group_by(curritem, next_item) %&gt;%
  summarise(n = n(), .groups = &quot;drop&quot;) %&gt;%
  group_by(curritem) %&gt;%
  mutate(P = round(n / sum(n) * 100, 2)) %&gt;%
  arrange(curritem, next_item) %&gt;%
  kable(caption = &quot;Table 7. Markov transition probabilities (%) between item types across the full fixation sequence.&quot;)</code></pre>
<table>
<caption>Table 7. Markov transition probabilities (%) between item types
across the full fixation sequence.</caption>
<thead>
<tr class="header">
<th align="left">curritem</th>
<th align="left">next_item</th>
<th align="right">n</th>
<th align="right">P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nonsingleton</td>
<td align="left">Nonsingleton</td>
<td align="right">8764</td>
<td align="right">44.13</td>
</tr>
<tr class="even">
<td align="left">Nonsingleton</td>
<td align="left">Singleton</td>
<td align="right">1187</td>
<td align="right">5.98</td>
</tr>
<tr class="odd">
<td align="left">Nonsingleton</td>
<td align="left">Target</td>
<td align="right">9909</td>
<td align="right">49.89</td>
</tr>
<tr class="even">
<td align="left">Singleton</td>
<td align="left">Nonsingleton</td>
<td align="right">1782</td>
<td align="right">44.64</td>
</tr>
<tr class="odd">
<td align="left">Singleton</td>
<td align="left">Singleton</td>
<td align="right">448</td>
<td align="right">11.22</td>
</tr>
<tr class="even">
<td align="left">Singleton</td>
<td align="left">Target</td>
<td align="right">1762</td>
<td align="right">44.14</td>
</tr>
<tr class="odd">
<td align="left">Target</td>
<td align="left">Nonsingleton</td>
<td align="right">2192</td>
<td align="right">19.58</td>
</tr>
<tr class="even">
<td align="left">Target</td>
<td align="left">Singleton</td>
<td align="right">488</td>
<td align="right">4.36</td>
</tr>
<tr class="odd">
<td align="left">Target</td>
<td align="left">Target</td>
<td align="right">8514</td>
<td align="right">76.06</td>
</tr>
</tbody>
</table>
<p>Examining all consecutive fixation pairs across the full scan
sequence, the transition matrix revealed a consistent picture of
target-directed search with modest singleton interference. Two
comparisons are theoretically central. First, P(Singleton -&gt; Target)
= 44.14% vs. P(Nonsingleton -&gt; Target) = 49.89%: after landing on the
singleton at any point in a trial, the eye was approximately 6
percentage points less likely to redirect immediately to the target than
after landing on a neutral nonsingleton distractor. Second, P(Singleton
-&gt; Nonsingleton) = 44.64% vs. P(Nonsingleton -&gt; Nonsingleton) =
44.13%: these two rates are very close to each other, indicating that
the reduction in target-directed transitions from the singleton is not
redistributed to other nonsingleton distractors. Instead, the “missing”
probability is absorbed by singleton refixations - P(Singleton -&gt;
Singleton) = 11.22%, nearly double the rate at which the eye returns to
the singleton from a nonsingleton position (P(Nonsingleton -&gt;
Singleton) = 5.98%). Once the target was found, the eye stayed: P(Target
-&gt; Target) = 76.06%, reflecting strong dwell tendency upon finding
the goal item.</p>
<pre class="r"><code># Extract P(next = Target | current = Singleton) 
sing_to_targ &lt;- pairs %&gt;%
  filter(curritem == &quot;Singleton&quot;) %&gt;%
  mutate(to_target = as.integer(next_item == &quot;Target&quot;),
         newtrial = factor(newtrial)) %&gt;%
  group_by(subjnum, newtrial) %&gt;%
  summarise(p_escape = mean(to_target), .groups = &quot;drop&quot;)

# ANOVA: Singleton -&gt; Target = 44.14%, whether the probability changes across all trials (learning trajectory)
MANOVA(data = sing_to_targ,
       subID = &quot;subjnum&quot;,
       dv = &quot;p_escape&quot;,
       within = &quot;newtrial&quot;,
       sph.correction = &quot;GG&quot;,
       digits = 2) %&gt;%
  EMMEANS(&quot;newtrial&quot;)</code></pre>
<pre><code>## 
##     * Data are aggregated to mean (across items/trials)
##     if there are &gt;=2 observations per subject and cell.
##     You may use Linear Mixed Model to analyze the data,
##     e.g., with subjects and items as level-2 clusters.</code></pre>
<pre><code>## 
## ====== ANOVA (Within-Subjects Design) ======
## 
## Descriptives:
## ──────────────────────────
##  &quot;newtrial&quot; Mean   S.D.  n
## ──────────────────────────
##   newtrial1 0.48 (0.15) 40
##   newtrial2 0.47 (0.16) 40
##   newtrial3 0.44 (0.15) 40
## ──────────────────────────
## Total sample size: N = 40
## 
## ANOVA Table:
## Dependent variable(s):      p_escape
## Between-subjects factor(s): –
## Within-subjects factor(s):  newtrial
## Covariate(s):               –
## ─────────────────────────────────────────────────────────────────────
##             MS  MSE  df1   df2    F     p     η²p [90% CI of η²p] η²G
## ─────────────────────────────────────────────────────────────────────
## newtrial  0.02 0.01 1.90 74.05 2.57  .086 .        .06 [.00, .16] .01
## ─────────────────────────────────────────────────────────────────────
## Sphericity correction method: GG (Greenhouse-Geisser)
## MSE = mean square error (the residual variance of the linear model)
## η²p = partial eta-squared = SS / (SS + SSE) = F * df1 / (F * df1 + df2)
## ω²p = partial omega-squared = (F - 1) * df1 / (F * df1 + df2 + 1)
## η²G = generalized eta-squared (see Olejnik &amp; Algina, 2003)
## Cohen’s f² = η²p / (1 - η²p)
## 
## Levene’s Test for Homogeneity of Variance:
## No between-subjects factors. No need to do the Levene’s test.
## 
## Mauchly’s Test of Sphericity:
## ───────────────────────────────
##           Mauchly&#39;s W     p    
## ───────────────────────────────
## newtrial       0.9466  .353    
## ───────────────────────────────
## 
## ------ EMMEANS (effect = &quot;newtrial&quot;) ------
## 
## Joint Tests of &quot;newtrial&quot;:
## ─────────────────────────────────────────────────────
##    Effect df1 df2     F     p     η²p [90% CI of η²p]
## ─────────────────────────────────────────────────────
##  newtrial   2  39 3.028  .060 .     .134 [.000, .290]
## ─────────────────────────────────────────────────────
## Note. Simple effects of repeated measures with 3 or more levels
## are different from the results obtained with SPSS MANOVA syntax.
## 
## Estimated Marginal Means of &quot;newtrial&quot;:
## ─────────────────────────────────────────
##  &quot;newtrial&quot; Mean [95% CI of Mean]    S.E.
## ─────────────────────────────────────────
##   newtrial1  0.480 [0.433, 0.527] (0.023)
##   newtrial2  0.468 [0.418, 0.518] (0.025)
##   newtrial3  0.438 [0.391, 0.485] (0.023)
## ─────────────────────────────────────────
## 
## Pairwise Comparisons of &quot;newtrial&quot;:
## ───────────────────────────────────────────────────────────────────────────────────
##               Contrast Estimate    S.E. df      t     p     Cohen’s d [95% CI of d]
## ───────────────────────────────────────────────────────────────────────────────────
##  newtrial2 - newtrial1   -0.012 (0.021) 39 -0.579 1.000      -0.100 [-0.535, 0.334]
##  newtrial3 - newtrial1   -0.042 (0.019) 39 -2.213  .098 .    -0.348 [-0.742, 0.045]
##  newtrial3 - newtrial2   -0.030 (0.017) 39 -1.747  .266      -0.248 [-0.603, 0.107]
## ───────────────────────────────────────────────────────────────────────────────────
## Pooled SD for computing Cohen’s d: 0.121
## P-value adjustment: Bonferroni method for 3 tests.
## 
## Disclaimer:
## By default, pooled SD is Root Mean Square Error (RMSE).
## There is much disagreement on how to compute Cohen’s d.
## You are completely responsible for setting `sd.pooled`.
## You might also use `effectsize::t_to_d()` to compute d.</code></pre>
<p>To test whether the singleton’s mid-sequence holding power weakens as
suppression is learned, we computed P(Singleton -&gt; Target) per
subject per trial position and submitted it to a one-way within-subjects
ANOVA. The effect of trial position was marginal, F(1.90, 74.05) = 2.57,
p = .086, η²p = .062. If anything, the trend ran counter to prediction -
escape-to-target probability decreased slightly from trial 1 to trial 3
(48.0%, 46.8%, 43.8%) rather than increasing. This counterintuitive
pattern almost certainly reflects selection bias: trial 3 captured
trials are drawn exclusively from participants who were hardest to
suppress, and such participants tend to be less efficient searchers
overall. No reliable learning-driven change in mid-sequence singleton
escape was observed.</p>
<pre class="r"><code># Summary with error bars for Target component
pc_ci &lt;- with(
  post_cap %&gt;% mutate(group_label = paste(&quot;T&quot;, newtrial, sep=&quot;&quot;)),
  cmErrBar(s2_target, subjnum, group_label, &quot;ci&quot;)
) %&gt;%
  rename(newtrial = group)

# barplot data
pc_stack &lt;- post_cap %&gt;%
  group_by(newtrial) %&gt;%
  summarise(Target = round(mean(s2_target) * 100, 2),
            Nonsingleton = round(mean(s2_nonsingleton) * 100, 2),
            Singleton = round(mean(s2_singleton) * 100, 2),
            .groups = &quot;drop&quot;) %&gt;%
  pivot_longer(cols = c(Target, Nonsingleton, Singleton),
               names_to = &quot;destination&quot;, values_to = &quot;pct&quot;) %&gt;%
  mutate(destination = factor(destination,
                               levels = c(&quot;Singleton&quot;, &quot;Nonsingleton&quot;, &quot;Target&quot;)))

ggplot(pc_stack,
       aes(x = newtrial, y = pct, fill = destination)) +
  geom_col(width = 0.6) +
  geom_errorbar(
    data = pc_ci %&gt;%
      mutate(newtrial = gsub(&quot;T&quot;,&quot;&quot;,newtrial)) %&gt;%
      mutate(y_base = pc_stack %&gt;%
               filter(destination %in% c(&quot;Singleton&quot;,&quot;Nonsingleton&quot;)) %&gt;%
               group_by(newtrial) %&gt;%
               summarise(base = sum(pct), .groups=&quot;drop&quot;) %&gt;%
               pull(base)),
    aes(x = newtrial,
        ymin = (minus + y_base) * 100,
        ymax = (plus + y_base) * 100),
    inherit.aes = FALSE, width = 0.15, linewidth = 0.9) +
  scale_fill_manual(
    values = c(&quot;Target&quot; = &quot;#2C3E50&quot;,
               &quot;Nonsingleton&quot; = &quot;#95A5A6&quot;,
               &quot;Singleton&quot; = &quot;#E74C3C&quot;),
    labels = c(&quot;Target&quot;, &quot;Nonsingleton&quot;, &quot;Singleton (re-fixation)&quot;)) +
  scale_y_continuous(limits = c(0, 105),
                     labels = scales::percent_format(scale = 1, accuracy = 1)) +
  labs(x = &quot;Trial Position within Group&quot;,
       y = &quot;Post-Capture Destination (%)&quot;,
       fill = &quot;Second Fixation&quot;) +
  manuscript_theme</code></pre>
<div class="figure">
<img src="p09_files/figure-html/unnamed-chunk-6-1.png" alt="Figure S8. Post-capture saccade destination (%) by trial position. Stacked bars show where the second fixation lands given the first fixation was captured. Error bars on Target component = 95% CI (Cousineau-Morey corrected)." width="768" />
<p class="caption">
Figure S8. Post-capture saccade destination (%) by trial position.
Stacked bars show where the second fixation lands given the first
fixation was captured. Error bars on Target component = 95% CI
(Cousineau-Morey corrected).
</p>
</div>
</div>
</div>
<div id="part-2-fixation-count-to-target---search-efficiency"
class="section level2">
<h2>Part 2 Fixation Count to Target - Search efficiency</h2>
<div id="data-preparation-1" class="section level3">
<h3>Data preparation</h3>
<pre class="r"><code># For each trial, find the earliest saccindex at which the eye reached the target.
# saccindex &gt;= 1 excludes the central fixation (pre-search period)
fix_count &lt;- search_full %&gt;%
  filter(!is.na(curritem), saccindex &gt;= 1) %&gt;%
  group_by(subjnum, trial, newtrial) %&gt;%
  summarise(
    # First_targ = 1: the eye went directly to the target as the first fixation
    first_targ = {
      tix &lt;- saccindex[curritem == &quot;Target&quot;]
      if (length(tix) == 0) NA_real_ else min(tix)
    },
    .groups = &quot;drop&quot;
  )

fix_count_clean &lt;- fix_count %&gt;%
  filter(!is.na(first_targ)) %&gt;%
  mutate(newtrial = factor(newtrial))

# Descriptives (trial-level)
fix_count_clean %&gt;%
  group_by(newtrial) %&gt;%
  summarise(M = round(mean(first_targ), 3),
            SD = round(sd(first_targ),   3),
            P_direct = round(mean(first_targ == 1) * 100, 2), # P_direct = % of trials where the target was fixated first.
            .groups = &quot;drop&quot;) %&gt;%
  kable(caption = &quot;Table 8. First-target fixation index by trial position.&quot;)</code></pre>
<table>
<caption>Table 8. First-target fixation index by trial
position.</caption>
<thead>
<tr class="header">
<th align="left">newtrial</th>
<th align="right">M</th>
<th align="right">SD</th>
<th align="right">P_direct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">2.049</td>
<td align="right">1.159</td>
<td align="right">38.71</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">2.018</td>
<td align="right">1.143</td>
<td align="right">39.74</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="right">2.053</td>
<td align="right">1.168</td>
<td align="right">38.59</td>
</tr>
</tbody>
</table>
</div>
<div id="anova" class="section level3">
<h3>ANOVA</h3>
<pre class="r"><code>fix_subj &lt;- fix_count_clean %&gt;%
  group_by(subjnum, newtrial) %&gt;%
  summarise(mean_fix = mean(first_targ), .groups = &quot;drop&quot;)

MANOVA(data = fix_subj,
       subID = &quot;subjnum&quot;,
       dv = &quot;mean_fix&quot;,
       within = &quot;newtrial&quot;,
       sph.correction = &quot;GG&quot;,
       digits = 2) %&gt;%
  EMMEANS(&quot;newtrial&quot;)</code></pre>
<pre><code>## 
##     * Data are aggregated to mean (across items/trials)
##     if there are &gt;=2 observations per subject and cell.
##     You may use Linear Mixed Model to analyze the data,
##     e.g., with subjects and items as level-2 clusters.</code></pre>
<pre><code>## 
## ====== ANOVA (Within-Subjects Design) ======
## 
## Descriptives:
## ──────────────────────────
##  &quot;newtrial&quot; Mean   S.D.  n
## ──────────────────────────
##   newtrial1 2.05 (0.43) 40
##   newtrial2 2.03 (0.48) 40
##   newtrial3 2.05 (0.43) 40
## ──────────────────────────
## Total sample size: N = 40
## 
## ANOVA Table:
## Dependent variable(s):      mean_fix
## Between-subjects factor(s): –
## Within-subjects factor(s):  newtrial
## Covariate(s):               –
## ─────────────────────────────────────────────────────────────────────
##             MS  MSE  df1   df2    F     p     η²p [90% CI of η²p] η²G
## ─────────────────────────────────────────────────────────────────────
## newtrial  0.01 0.02 1.79 69.94 0.61  .528          .02 [.00, .08] .00
## ─────────────────────────────────────────────────────────────────────
## Sphericity correction method: GG (Greenhouse-Geisser)
## MSE = mean square error (the residual variance of the linear model)
## η²p = partial eta-squared = SS / (SS + SSE) = F * df1 / (F * df1 + df2)
## ω²p = partial omega-squared = (F - 1) * df1 / (F * df1 + df2 + 1)
## η²G = generalized eta-squared (see Olejnik &amp; Algina, 2003)
## Cohen’s f² = η²p / (1 - η²p)
## 
## Levene’s Test for Homogeneity of Variance:
## No between-subjects factors. No need to do the Levene’s test.
## 
## Mauchly’s Test of Sphericity:
## ───────────────────────────────
##           Mauchly&#39;s W     p    
## ───────────────────────────────
## newtrial       0.8847  .098 .  
## ───────────────────────────────
## 
## ------ EMMEANS (effect = &quot;newtrial&quot;) ------
## 
## Joint Tests of &quot;newtrial&quot;:
## ─────────────────────────────────────────────────────
##    Effect df1 df2     F     p     η²p [90% CI of η²p]
## ─────────────────────────────────────────────────────
##  newtrial   2  39 0.499  .611       .025 [.000, .119]
## ─────────────────────────────────────────────────────
## Note. Simple effects of repeated measures with 3 or more levels
## are different from the results obtained with SPSS MANOVA syntax.
## 
## Estimated Marginal Means of &quot;newtrial&quot;:
## ─────────────────────────────────────────
##  &quot;newtrial&quot; Mean [95% CI of Mean]    S.E.
## ─────────────────────────────────────────
##   newtrial1  2.054 [1.917, 2.191] (0.068)
##   newtrial2  2.029 [1.875, 2.183] (0.076)
##   newtrial3  2.054 [1.917, 2.191] (0.068)
## ─────────────────────────────────────────
## 
## Pairwise Comparisons of &quot;newtrial&quot;:
## ───────────────────────────────────────────────────────────────────────────────────
##               Contrast Estimate    S.E. df      t     p     Cohen’s d [95% CI of d]
## ───────────────────────────────────────────────────────────────────────────────────
##  newtrial2 - newtrial1   -0.025 (0.030) 39 -0.834 1.000      -0.150 [-0.602, 0.301]
##  newtrial3 - newtrial1    0.000 (0.022) 39  0.015 1.000       0.002 [-0.333, 0.337]
##  newtrial3 - newtrial2    0.025 (0.026) 39  0.974 1.000       0.153 [-0.239, 0.544]
## ───────────────────────────────────────────────────────────────────────────────────
## Pooled SD for computing Cohen’s d: 0.167
## P-value adjustment: Bonferroni method for 3 tests.
## 
## Disclaimer:
## By default, pooled SD is Root Mean Square Error (RMSE).
## There is much disagreement on how to compute Cohen’s d.
## You are completely responsible for setting `sd.pooled`.
## You might also use `effectsize::t_to_d()` to compute d.</code></pre>
<p>For each trial we computed the saccade index at which the eye first
reached the target (saccindex ≥ 1). Subject-level means per trial
position were submitted to a one-way within-subjects ANOVA. The ANOVA
confirmed a completely flat result: F(1.793, 69.938) = 0.61, p = .53,
η²p = .015. Trial-position means were almost identical - 2.054 (SD =
.43) on trial 1, 2.029 (SD = 0.48) on trial 2, and 2.054 (SD = 0.43) on
Trial 3. All pairwise contrasts were non-significant after Bonferroni
correction. The number of fixations required to reach the target was
entirely stable across the suppression learning</p>
</div>
<div id="plot" class="section level3">
<h3>Plot</h3>
<pre class="r"><code># Panel A: mean per newtrial
fc_sum &lt;- with(
  fix_subj %&gt;% mutate(group_label = as.character(newtrial)),
  cmErrBar(mean_fix, subjnum, group_label, &quot;ci&quot;)
) %&gt;% rename(newtrial = group)

p_fc_mean &lt;- ggplot(fc_sum,
                    aes(x = newtrial, y = mean, group = 1)) +
  geom_errorbar(aes(ymin = minus, ymax = plus),
                width = 0.15, linewidth = 1.1) +
  geom_line(linewidth = 1.1, color = &quot;#2C3E50&quot;) +
  geom_point(size = 4,  color = &quot;#2C3E50&quot;) +
  scale_y_continuous(limits = c(1, 3)) +
  labs(x = &quot;Trial Position within Group&quot;,
       y = &quot;Mean Fixations before Target&quot;) +
  manuscript_theme

# Panel B: histogram of first_targ distribution
fix_dist &lt;- fix_count_clean %&gt;%
  filter(first_targ &lt;= 8) %&gt;%
  mutate(newtrial = paste0(&quot;T&quot;, newtrial))

p_fc_dist &lt;- ggplot(fix_dist,
                    aes(x = factor(first_targ), fill = newtrial)) +
  geom_bar(position = &quot;dodge&quot;, alpha = 0.85) +
  scale_fill_manual(
    values = c(&quot;T1&quot; = &quot;#2C3E50&quot;, &quot;T2&quot; = &quot;#7F8C8D&quot;, &quot;T3&quot; = &quot;#BDC3C7&quot;)) +
  labs(x = &quot;First-Target Fixation Index&quot;,
       y = &quot;Trial Count&quot;,
       fill = &quot;Trial Position&quot;) +
  manuscript_theme

p_fc_mean + p_fc_dist + plot_layout(widths = c(1, 1.4))</code></pre>
<div class="figure">
<img src="p09_files/figure-html/unnamed-chunk-9-1.png" alt="Figure 1. Left: mean first-target fixation index (± 95% CI) by trial position. Right: distribution of first-target fixation index pooled across trial positions. Error bars = 95% CI (Cousineau-Morey corrected)." width="960" />
<p class="caption">
Figure 1. Left: mean first-target fixation index (± 95% CI) by trial
position. Right: distribution of first-target fixation index pooled
across trial positions. Error bars = 95% CI (Cousineau-Morey corrected).
</p>
</div>
<p>In the left panel, the three points sit essentially on top of each
other at about 2.10, flat across trial positions. The error bars are
narrow and fully overlapping. This is a clean visual confirmation of no
trend whatever.</p>
<p>In the right panel, the distribution of first-target fixation index
showed how many fixations did the eyes make before it first landed on
the target. The vast majority of trials were resolved within the first
two fixations. Crucially, the distributions were nearly identical in
shape: the relative proportion of trials at each fixation index is
stable across trial 1, trial 2, and trial 3. No trial position
demonstrated a systematic shift toward lower indices that would indicate
more direct target acquisition, nor a shift toward higher indices
indicating longer search paths. This shape invariance was the visual
complement to the flat ANOVA result.</p>
</div>
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>Both within-trial analyses returned strong null results. Post-capture
recovery and search efficiency were completely invariant across the
three-trial suppression learning sequence, despite singleton
first-fixation rate dropping substantially across the same trials.</p>
<p>This creates a sharp mechanistic dissociation: suppression learning
is exclusively a pre-saccadic phenomenon. It operates during the initial
oculomotor planning stage; while the eye is still at the central
fixation point and exerts no downstream influence on search behavior
once the first saccade is executed. Suppression does not make
within-trial search smarter or more efficient; it simply prevents the
eye from being misdirected at the very first step. Once a saccade is
underway, the subsequent fixation sequence unfolds almost identically
regardless of how much learning has accumulated across the trial
group.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
