<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 12: HMM Stage 3 - Transfer Prediction (VST → RSVP)</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
<li>
  <a href="p11.html">Portfolio 11</a>
</li>
<li>
  <a href="p12.html">Portfolio 12</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 12: HMM Stage 3 - Transfer
Prediction (VST → RSVP)</h1>

</div>


<div id="background" class="section level1">
<h1>Background</h1>
<p>Portfolios 10 and 11 established that a 2-state joint HMM (item type
+ fixation duration) recovers two attentional modes - Efficient Search
and Distractor Engagement - and that the VD-CD difference in state
prevalence captures the learned distractor suppression signal. Portfolio
11 extracted five participant-level features from the VST-first group (n
= 24) that quantify how quickly and how completely each individual
learned to suppress the consistent distractor:</p>
<ul>
<li>Learning slope: rate of increase in P(Efficient Search) across
trials.</li>
<li>Transition trial: the trial at which the 5-trial rolling mean of
P(Efficient Search) first exceeds 0.50.</li>
<li>End-state P(Efficient Search): mean P(Efficient Search) in the final
experimental block.</li>
<li>Overall suppression score: mean VD-CD difference in P(Distractor
Engagement) across blocks.</li>
<li>Suppression growth: late - early change in the suppression
score.</li>
</ul>
<p>The central question for Stage 3 is whether these HMM-derived
individual differences in VST suppression learning predict cross-task
transfer to the RSVP task. The VST-first group completed the Visual
Search Task before the RSVP task, so any relationship between VST
learning features and RSVP outcomes would constitute evidence that the
latent suppression process captured by the HMM generalizes beyond the
training task.</p>
<p>The primary RSVP transfer outcome is Blink_CD - the attentional blink
magnitude for the consistent distractor color, computed as the
difference in target accuracy between lag 8 and lag 2, where lag is the
distance in stream positions between a distractor (a hashtag) and the
single target that follows it. If learned suppression transfers,
participants who showed stronger or faster suppression learning in the
VST should show a reduced attentional blink for the consistent
distractor color in the RSVP task.</p>
<p>This approach follows the logic of individual-differences transfer
designs used in the learned attention literature, where the strength of
statistical learning during training predicts the magnitude of transfer
effects in a novel task.</p>
</div>
<div id="goals" class="section level1">
<h1>Goals</h1>
<ol style="list-style-type: decimal">
<li>Load the participant-level HMM features from Portfolio 11 and the
RSVP transfer outcomes, and merge by participant.</li>
<li>Examine descriptive statistics and distributions of the RSVP outcome
(Blink_CD) and all HMM predictors.</li>
<li>Run bivariate correlations between each HMM feature and Blink_CD to
identify which aspects of suppression learning are associated with
transfer.</li>
<li>Fit a multiple regression with the most promising predictors to test
their joint and unique contributions.</li>
<li>Visualize the key predictor–outcome relationships.</li>
<li>Evaluate assumptions (normality, influential cases) and report
results in APA style.</li>
</ol>
</div>
<div id="setup" class="section level1">
<h1>Setup</h1>
<pre class="r"><code>rm(list = ls())

library(tidyverse)</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.1     ✔ stringr   1.5.2
## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<pre class="r"><code>library(readxl)
library(knitr)
library(patchwork)
library(car)</code></pre>
<pre><code>## Loading required package: carData
## 
## Attaching package: &#39;car&#39;
## 
## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode
## 
## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<pre class="r"><code>select &lt;- dplyr::select
filter &lt;- dplyr::filter</code></pre>
<pre class="r"><code># Plot theme (matching manuscript style from p10/p11)
axis_text_size &lt;- 14
axis_tick_text_size &lt;- 12
graph_color &lt;- &quot;black&quot;
axis_tick_length &lt;- 0.25
axis_tick_units &lt;- &quot;cm&quot;
axis_thickness &lt;- 1

manuscript_theme &lt;- theme_classic() +
  theme(
    axis.line = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.title = element_text(size = axis_text_size),
    axis.text = element_text(colour = graph_color, size = axis_tick_text_size),
    axis.ticks = element_line(linewidth = axis_thickness, colour = graph_color),
    axis.ticks.length.y = unit(axis_tick_length, axis_tick_units),
    axis.ticks.length.x = unit(axis_tick_length, axis_tick_units),
    legend.position = &quot;top&quot;,
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    text = element_text(size = axis_tick_text_size)
  )

# Consistent color palette
col_efficient &lt;- &quot;#1F77B4&quot;
col_engaged &lt;- &quot;#D62728&quot;</code></pre>
</div>
<div id="data-loading-and-merging" class="section level1">
<h1>Data Loading and Merging</h1>
<div id="load-hmm-features-from-portfolio-11" class="section level2">
<h2>Load HMM Features (from Portfolio 11)</h2>
<pre class="r"><code># Participant-level HMM features extracted in p11 (VST-first group, n = 24)
hmm_features &lt;- read_csv(&quot;output/stage2_participant_features_vst_first.csv&quot;,
                         show_col_types = FALSE)</code></pre>
</div>
<div id="load-rsvp-transfer-outcomes" class="section level2">
<h2>Load RSVP Transfer Outcomes</h2>
<pre class="r"><code># RSVP accuracy data
rsvp_acc &lt;- read_excel(
  &quot;summary/RSVP_DataSummary_SL_EyeTracking_Final.xlsx&quot;,
  sheet = &quot;ACC&quot;
)

# Filter to VST-first group (Order == &quot;VST_RSVP&quot;)
rsvp_vst &lt;- rsvp_acc %&gt;%
  filter(Order == &quot;VST_RSVP&quot;) %&gt;%
  mutate(subjnum = as.integer(subjnum))</code></pre>
<p>Each RSVP stream contains a distractor (a hashtag) followed by a
single target; lag indexes the number of stream positions between them.
The dataset contains target accuracy for each condition (CD, ND,
VD_Match, VD_Mismatch) at two lags (2 and 8), along with pre-computed
attentional blink scores (Blink = target accuracy at lag 8 − target
accuracy at lag 2). The primary outcome is Blink_CD: the attentional
blink magnitude for the consistent distractor color.</p>
</div>
<div id="merge-datasets" class="section level2">
<h2>Merge Datasets</h2>
<pre class="r"><code># Merge by subject number. We use inner_join (not left_join) on purpose: any participant who has features but no RSVP record (or vice versa) is dropped from analysis, which keeps `transfer_data` to the participants who can contribute to every model below. The setdiff checks below report whether anyone was lost so a silent drop never goes unnoticed.
transfer_data &lt;- hmm_features %&gt;%
  inner_join(rsvp_vst, by = &quot;subjnum&quot;)


# Diagnostic: who, if anyone, was lost in the merge
hmm_only &lt;- setdiff(hmm_features$subjnum, rsvp_vst$subjnum)
rsvp_only &lt;- setdiff(rsvp_vst$subjnum, hmm_features$subjnum)
if (length(hmm_only) &gt; 0) cat(&quot;  Participants in HMM but not RSVP:&quot;, hmm_only, &quot;\n&quot;)
if (length(rsvp_only) &gt; 0) cat(&quot;  Participants in RSVP but not HMM:&quot;, rsvp_only, &quot;\n&quot;)
if (length(hmm_only) == 0 &amp; length(rsvp_only) == 0) cat(&quot;  All participants matched.\n&quot;)</code></pre>
<pre><code>##   All participants matched.</code></pre>
</div>
</div>
<div id="descriptive-statistics" class="section level1">
<h1>Descriptive Statistics</h1>
<div id="rsvp-outcome-blink_cd" class="section level2">
<h2>RSVP Outcome: Blink_CD</h2>
<pre class="r"><code># Compute M/SD/Min/Max for each of the four blink measures, producing one wide row with columns like `Blink_CD_M`, `Blink_CD_SD`, ...
# The two pivots then reshape this into a tidy measure x {M,SD,Min,Max} table:
## pivot_longer&#39;s `names_pattern = &quot;(.+)_(M|SD|Min|Max)&quot;` splits each column name into a measure stem and a statistic suffix
## pivot_wider then puts each statistic in its own column
blink_summary &lt;- transfer_data %&gt;%
  summarise(
    across(c(Blink_CD, Blink_ND, Blink_VD_Match, Blink_VD_Mismatch),
           list(M = ~mean(., na.rm = TRUE),
                SD = ~sd(., na.rm = TRUE),
                Min = ~min(., na.rm = TRUE),
                Max = ~max(., na.rm = TRUE)),
           .names = &quot;{.col}_{.fn}&quot;)
  ) %&gt;%
  pivot_longer(everything(),
               names_to = c(&quot;measure&quot;, &quot;stat&quot;),
               names_pattern = &quot;(.+)_(M|SD|Min|Max)&quot;) %&gt;%
  pivot_wider(names_from = stat, values_from = value)</code></pre>
<pre><code>## Warning: Values from `value` are not uniquely identified; output will contain list-cols.
## • Use `values_fn = list` to suppress this warning.
## • Use `values_fn = {summary_fun}` to summarise duplicates.
## • Use the following dplyr code to identify duplicates.
##   {data} |&gt;
##   dplyr::summarise(n = dplyr::n(), .by = c(measure, stat)) |&gt;
##   dplyr::filter(n &gt; 1L)</code></pre>
<pre class="r"><code>kable(blink_summary, digits = 3,
      caption = &quot;Table 1. Descriptive statistics for RSVP attentional blink scores (VST-first group).&quot;)</code></pre>
<table>
<caption>Table 1. Descriptive statistics for RSVP attentional blink
scores (VST-first group).</caption>
<thead>
<tr class="header">
<th align="left">measure</th>
<th align="left">M</th>
<th align="left">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Blink_CD</td>
<td align="left">0.06312693, -0.08494208, 0.23865546</td>
<td align="left">0.1021727</td>
</tr>
<tr class="even">
<td align="left">Blink_ND</td>
<td align="left">0.05790576, -0.04712405, 0.19504644</td>
<td align="left">0.04487119</td>
</tr>
<tr class="odd">
<td align="left">Blink_VD_Match</td>
<td align="left">0.07318922, -0.35714286, 0.60000000</td>
<td align="left">0.235381</td>
</tr>
<tr class="even">
<td align="left">Blink_VD_Mismatch</td>
<td align="left">0.06016576, -0.24137931, 0.33625731</td>
<td align="left">0.1252788</td>
</tr>
</tbody>
</table>
<pre class="r"><code>ggplot(transfer_data, aes(x = Blink_CD)) +
  geom_histogram(binwidth = 0.05, fill = col_efficient, color = &quot;white&quot;, alpha = 0.8) +
  geom_vline(xintercept = 0, linetype = &quot;dashed&quot;, color = &quot;gray40&quot;) +
  geom_vline(xintercept = mean(transfer_data$Blink_CD, na.rm = TRUE),
             linetype = &quot;solid&quot;, color = col_engaged, linewidth = 1) +
  labs(x = &quot;Blink_CD (Lag 8 - Lag 2 Accuracy)&quot;,
       y = &quot;Count&quot;) +
  annotate(&quot;text&quot;, x = mean(transfer_data$Blink_CD, na.rm = TRUE), y = Inf,
           label = &quot;Mean&quot;, vjust = 2, hjust = -0.2, color = col_engaged, size = 5) +
  manuscript_theme</code></pre>
<div class="figure">
<img src="p12_files/figure-html/blink-distribution-1.png" alt="Figure 1. Distribution of attentional blink magnitude for the consistent distractor color (Blink_CD). Each bar represents a VST-first participant. Positive values indicate a standard attentional blink (better target accuracy at lag 8 than lag 2); negative values indicate a reversed blink." width="768" />
<p class="caption">
Figure 1. Distribution of attentional blink magnitude for the consistent
distractor color (Blink_CD). Each bar represents a VST-first
participant. Positive values indicate a standard attentional blink
(better target accuracy at lag 8 than lag 2); negative values indicate a
reversed blink.
</p>
</div>
</div>
<div id="hmm-predictor-summary" class="section level2">
<h2>HMM Predictor Summary</h2>
<pre class="r"><code># Same wide-summarise -&gt; pivot pattern as the blink summary above, applied to the five HMM predictors. We carry M and SD only (not Min/Max) because the predictors are bounded transformations of probabilities or trial indices and their range is less informative than the spread.
predictor_summary &lt;- transfer_data %&gt;%
  summarise(
    across(c(learning_slope, transition_trial, end_p_efficient,
             overall_suppress, suppress_growth),
           list(M = ~mean(., na.rm = TRUE),
                SD = ~sd(., na.rm = TRUE)),
           .names = &quot;{.col}_{.fn}&quot;)
  ) %&gt;%
  pivot_longer(everything(),
               names_to = c(&quot;feature&quot;, &quot;stat&quot;),
               names_pattern = &quot;(.+)_(M|SD)&quot;) %&gt;%
  pivot_wider(names_from = stat, values_from = value)

kable(predictor_summary, digits = 4,
      caption = &quot;Table 2. Descriptive statistics for HMM-derived predictors (VST-first group).&quot;)</code></pre>
<table>
<caption>Table 2. Descriptive statistics for HMM-derived predictors
(VST-first group).</caption>
<thead>
<tr class="header">
<th align="left">feature</th>
<th align="right">M</th>
<th align="right">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">learning_slope</td>
<td align="right">-0.0001</td>
<td align="right">0.0002</td>
</tr>
<tr class="even">
<td align="left">transition_trial</td>
<td align="right">122.8824</td>
<td align="right">82.9065</td>
</tr>
<tr class="odd">
<td align="left">end_p_efficient</td>
<td align="right">0.2967</td>
<td align="right">0.0555</td>
</tr>
<tr class="even">
<td align="left">overall_suppress</td>
<td align="right">-0.0032</td>
<td align="right">0.0238</td>
</tr>
<tr class="odd">
<td align="left">suppress_growth</td>
<td align="right">0.0005</td>
<td align="right">0.0555</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="bivariate-correlations" class="section level1">
<h1>Bivariate Correlations</h1>
<p>We first examine individual Pearson correlations between each HMM
feature and Blink_CD. This step identifies which features show the
strongest zero-order relationships with transfer before entering them
into a multiple regression.</p>
<p>The expected sign of each correlation differs across features.
Because a smaller blink (lower Blink_CD value) reflects better RSVP
performance, stronger or faster suppression learning during the VST
should produce a negative correlation with Blink_CD for
<code>learning_slope</code>, <code>end_p_efficient</code>,
<code>overall_suppress</code>, and <code>suppress_growth</code> - i.e.,
participants who learned more should have less blink.
<code>transition_trial</code> runs in the opposite direction: faster
learning yields a lower trial number, so the expected correlation with
Blink_CD is positive (low transition trial paired with low blink). The
same sign logic applies to the regression coefficients in the model
below.</p>
<pre class="r"><code># Predictor vector (used here and reused throughout the file) plus a named lookup for nicely formatted labels in tables and figures.
predictors &lt;- c(&quot;learning_slope&quot;, &quot;transition_trial&quot;, &quot;end_p_efficient&quot;,
                &quot;overall_suppress&quot;, &quot;suppress_growth&quot;)

predictor_labels &lt;- c(
  learning_slope = &quot;Learning Slope&quot;,
  transition_trial = &quot;Transition Trial&quot;,
  end_p_efficient = &quot;End-State P(Efficient)&quot;,
  overall_suppress = &quot;Overall Suppression&quot;,
  suppress_growth = &quot;Suppression Growth&quot;
)

# Run bivariate correlations with map_dfr (apply the function to each predictor name and row-bind the results into a tibble). 
cor_results &lt;- map_dfr(predictors, function(pred) {
  d &lt;- transfer_data %&gt;%
    select(Blink_CD, all_of(pred)) %&gt;%
    drop_na()

  ct &lt;- cor.test(d[[pred]], d$Blink_CD)

  tibble(
    Predictor = predictor_labels[pred],
    variable = pred,
    r = ct$estimate,
    t = ct$statistic,
    df = ct$parameter,
    p = ct$p.value,
    CI_lower = ct$conf.int[1],
    CI_upper = ct$conf.int[2],
    n = nrow(d)
  )
})

kable(cor_results %&gt;% select(Predictor, n, r, t, df, p, CI_lower, CI_upper),
      digits = c(0, 0, 3, 2, 0, 4, 3, 3),
      caption = &quot;Table 3. Bivariate Pearson correlations between HMM features and Blink_CD.&quot;,
      col.names = c(&quot;Predictor&quot;, &quot;n&quot;, &quot;r&quot;, &quot;t&quot;, &quot;df&quot;, &quot;p&quot;, &quot;95% CI Lower&quot;, &quot;95% CI Upper&quot;))</code></pre>
<table>
<caption>Table 3. Bivariate Pearson correlations between HMM features
and Blink_CD.</caption>
<colgroup>
<col width="30%" />
<col width="4%" />
<col width="9%" />
<col width="8%" />
<col width="4%" />
<col width="9%" />
<col width="17%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="right">n</th>
<th align="right">r</th>
<th align="right">t</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">95% CI Lower</th>
<th align="right">95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Learning Slope</td>
<td align="right">24</td>
<td align="right">-0.350</td>
<td align="right">-1.75</td>
<td align="right">22</td>
<td align="right">0.0934</td>
<td align="right">-0.660</td>
<td align="right">0.062</td>
</tr>
<tr class="even">
<td align="left">Transition Trial</td>
<td align="right">17</td>
<td align="right">0.110</td>
<td align="right">0.43</td>
<td align="right">15</td>
<td align="right">0.6730</td>
<td align="right">-0.391</td>
<td align="right">0.561</td>
</tr>
<tr class="odd">
<td align="left">End-State P(Efficient)</td>
<td align="right">24</td>
<td align="right">-0.363</td>
<td align="right">-1.83</td>
<td align="right">22</td>
<td align="right">0.0815</td>
<td align="right">-0.668</td>
<td align="right">0.048</td>
</tr>
<tr class="even">
<td align="left">Overall Suppression</td>
<td align="right">24</td>
<td align="right">0.233</td>
<td align="right">1.12</td>
<td align="right">22</td>
<td align="right">0.2735</td>
<td align="right">-0.188</td>
<td align="right">0.582</td>
</tr>
<tr class="odd">
<td align="left">Suppression Growth</td>
<td align="right">24</td>
<td align="right">0.188</td>
<td align="right">0.90</td>
<td align="right">22</td>
<td align="right">0.3801</td>
<td align="right">-0.233</td>
<td align="right">0.549</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Pre-compute summary counts for inline reporting in the prose below.
sig_predictors &lt;- cor_results %&gt;% filter(p &lt; .05)
trend_predictors &lt;- cor_results %&gt;% filter(p &gt;= .05 &amp; p &lt; .10)

n_sig &lt;- nrow(sig_predictors)
n_trend &lt;- nrow(trend_predictors)

# &quot;Strongest&quot; = predictor with the smallest p-value (which here also corresponds to the largest |r| up to df differences across predictors).
strongest &lt;- cor_results %&gt;% arrange(p) %&gt;% slice(1)</code></pre>
<div id="scatterplots-each-hmm-feature-blink_cd" class="section level2">
<h2>Scatterplots: Each HMM Feature × Blink_CD</h2>
<pre class="r"><code>scatter_data &lt;- transfer_data %&gt;%
  select(subjnum, Blink_CD, all_of(predictors)) %&gt;%
  pivot_longer(cols = all_of(predictors),
               names_to = &quot;feature&quot;, values_to = &quot;value&quot;) %&gt;%
  mutate(feature_label = unname(predictor_labels[feature]))

ggplot(scatter_data, aes(x = value, y = Blink_CD)) +
  geom_point(size = 2.5, color = &quot;gray35&quot;, alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;, se = TRUE,
              color = &quot;black&quot;, fill = &quot;gray80&quot;, linewidth = 1) +
  facet_wrap(~ feature_label, scales = &quot;free_x&quot;, ncol = 3) +
  labs(x = &quot;HMM Feature Value&quot;, y = &quot;Blink_CD&quot;) +
  manuscript_theme +
  theme(strip.text = element_text(size = 11))</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 7 rows containing non-finite outside the scale range
## (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 7 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<div class="figure">
<img src="p12_files/figure-html/scatter-all-1.png" alt="Figure 2. Bivariate relationships between each HMM feature and Blink_CD. Each point is one VST-first participant. The regression line (with 95% CI band) shows the direction and strength of the linear association. Stronger suppression learning during VST (e.g., steeper learning slope, higher end-state efficiency) should predict a smaller attentional blink for the consistent distractor color in the RSVP task." width="1152" />
<p class="caption">
Figure 2. Bivariate relationships between each HMM feature and Blink_CD.
Each point is one VST-first participant. The regression line (with 95%
CI band) shows the direction and strength of the linear association.
Stronger suppression learning during VST (e.g., steeper learning slope,
higher end-state efficiency) should predict a smaller attentional blink
for the consistent distractor color in the RSVP task.
</p>
</div>
</div>
</div>
<div id="predictor-intercorrelations" class="section level1">
<h1>Predictor Intercorrelations</h1>
<p>Before fitting the multiple regression, we check intercorrelations
among predictors to assess potential multicollinearity.</p>
<pre class="r"><code># Compute the full predictor x predictor correlation matrix. 
# We drop_na() first to align all pairwise correlations on the same set of complete cases
# the `use = &quot;pairwise.complete.obs&quot;` argument is then a defensive default in case any NAs slip through. 
# High intercorrelations (|r| &gt; .70 is a common rule of thumb) flag potential multicollinearity that would inflate VIFs and destabilise the unique-effect estimates in the multiple regression.
pred_matrix &lt;- transfer_data %&gt;%
  select(all_of(predictors)) %&gt;%
  drop_na()

cor_matrix &lt;- cor(pred_matrix, use = &quot;pairwise.complete.obs&quot;)

kable(round(cor_matrix, 3),
      caption = &quot;Table 4. Intercorrelation matrix among HMM predictors.&quot;)</code></pre>
<table style="width:100%;">
<caption>Table 4. Intercorrelation matrix among HMM
predictors.</caption>
<colgroup>
<col width="17%" />
<col width="15%" />
<col width="17%" />
<col width="16%" />
<col width="17%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">learning_slope</th>
<th align="right">transition_trial</th>
<th align="right">end_p_efficient</th>
<th align="right">overall_suppress</th>
<th align="right">suppress_growth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">learning_slope</td>
<td align="right">1.000</td>
<td align="right">0.235</td>
<td align="right">0.359</td>
<td align="right">0.140</td>
<td align="right">-0.425</td>
</tr>
<tr class="even">
<td align="left">transition_trial</td>
<td align="right">0.235</td>
<td align="right">1.000</td>
<td align="right">-0.230</td>
<td align="right">0.479</td>
<td align="right">0.422</td>
</tr>
<tr class="odd">
<td align="left">end_p_efficient</td>
<td align="right">0.359</td>
<td align="right">-0.230</td>
<td align="right">1.000</td>
<td align="right">-0.286</td>
<td align="right">-0.607</td>
</tr>
<tr class="even">
<td align="left">overall_suppress</td>
<td align="right">0.140</td>
<td align="right">0.479</td>
<td align="right">-0.286</td>
<td align="right">1.000</td>
<td align="right">0.396</td>
</tr>
<tr class="odd">
<td align="left">suppress_growth</td>
<td align="right">-0.425</td>
<td align="right">0.422</td>
<td align="right">-0.607</td>
<td align="right">0.396</td>
<td align="right">1.000</td>
</tr>
</tbody>
</table>
<pre class="r"><code>cor_long &lt;- as.data.frame(as.table(cor_matrix)) %&gt;%
  rename(Var1 = Var1, Var2 = Var2, r = Freq) %&gt;%
  mutate(
    Var1 = unname(predictor_labels[as.character(Var1)]),
    Var2 = unname(predictor_labels[as.character(Var2)])
  )

ggplot(cor_long, aes(x = Var1, y = Var2, fill = r)) +
  geom_tile(color = &quot;white&quot;) +
  geom_text(aes(label = sprintf(&quot;%.2f&quot;, r)), size = 3.5) +
  scale_fill_gradient2(low = col_engaged, mid = &quot;white&quot;, high = col_efficient,
                       midpoint = 0, limits = c(-1, 1)) +
  labs(x = NULL, y = NULL, fill = &quot;r&quot;) +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10))</code></pre>
<div class="figure">
<img src="p12_files/figure-html/correlation-heatmap-1.png" alt="Figure 3. Heatmap of intercorrelations among HMM predictors. Darker blue = stronger positive correlation; darker red = stronger negative correlation. High intercorrelations (|r| &gt; .70) would signal multicollinearity concerns for the multiple regression." width="768" />
<p class="caption">
Figure 3. Heatmap of intercorrelations among HMM predictors. Darker blue
= stronger positive correlation; darker red = stronger negative
correlation. High intercorrelations (|r| &gt; .70) would signal
multicollinearity concerns for the multiple regression.
</p>
</div>
</div>
<div id="multiple-regression-hmm-features-predicting-blink_cd"
class="section level1">
<h1>Multiple Regression: HMM Features Predicting Blink_CD</h1>
<p>We fit a multiple regression entering all five HMM features as
simultaneous predictors of Blink_CD. This tests whether the features
carry unique predictive information about transfer beyond their shared
variance. With <em>n</em> = 24 and 5 predictors, the model has only 18
residual degrees of freedom; estimates of unique predictor contributions
are therefore underpowered, and small-to-moderate true effects may not
reach significance even if they exist. The standardized coefficients
reported below should be read alongside the bivariate correlations
rather than as a definitive test of any single feature’s predictive
value.</p>
<pre class="r"><code># Fit the full model (listwise deletion for transition_trial NAs)
reg_data &lt;- transfer_data %&gt;%
  select(subjnum, Blink_CD, all_of(predictors)) %&gt;%
  drop_na()

model_full &lt;- lm(Blink_CD ~ learning_slope + transition_trial +
                   end_p_efficient + overall_suppress + suppress_growth,
                 data = reg_data)

summary(model_full)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Blink_CD ~ learning_slope + transition_trial + end_p_efficient + 
##     overall_suppress + suppress_growth, data = reg_data)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.172317 -0.035390  0.000403  0.052985  0.165013 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)       1.397e-01  1.885e-01   0.741    0.474
## learning_slope   -9.542e+01  1.576e+02  -0.606    0.557
## transition_trial  6.668e-05  4.148e-04   0.161    0.875
## end_p_efficient  -3.511e-01  5.747e-01  -0.611    0.554
## overall_suppress  6.424e-01  1.189e+00   0.540    0.600
## suppress_growth  -1.246e-01  6.918e-01  -0.180    0.860
## 
## Residual standard error: 0.1047 on 11 degrees of freedom
## Multiple R-squared:  0.1463, Adjusted R-squared:  -0.2418 
## F-statistic: 0.377 on 5 and 11 DF,  p-value: 0.8543</code></pre>
<div id="regression-diagnostics" class="section level2">
<h2>Regression Diagnostics</h2>
<pre class="r"><code># Variance Inflation Factors
vif_values &lt;- vif(model_full)
print(round(vif_values, 2))</code></pre>
<pre><code>##   learning_slope transition_trial  end_p_efficient overall_suppress 
##             1.77             1.73             1.64             1.47 
##  suppress_growth 
##             2.49</code></pre>
<pre class="r"><code>vif_concern &lt;- any(vif_values &gt; 5)
if (vif_concern) {
  cat(&quot;\nWARNING: VIF &gt; 5 detected - multicollinearity may inflate standard errors.\n&quot;)
} else {
  cat(&quot;\nAll VIFs &lt; 5 - no severe multicollinearity concerns.\n&quot;)
}</code></pre>
<pre><code>## 
## All VIFs &lt; 5 - no severe multicollinearity concerns.</code></pre>
<pre class="r"><code># `plot.lm()` returns four diagnostic panels in sequence; par(mfrow) lays
# them out in a 2x2 grid so they render as one figure. Reset to single-panel
# afterwards so subsequent base-R plots are not affected.
par(mfrow = c(2, 2))
plot(model_full)</code></pre>
<div class="figure">
<img src="p12_files/figure-html/diagnostic-plots-1.png" alt="Figure 4. Regression diagnostic plots. Top-left: residuals vs. fitted (check for non-linearity and heteroscedasticity). Top-right: Q-Q plot (check for normality of residuals). Bottom-left: scale-location (check for homoscedasticity). Bottom-right: residuals vs. leverage (identify influential cases with high Cook's distance)." width="960" />
<p class="caption">
Figure 4. Regression diagnostic plots. Top-left: residuals vs. fitted
(check for non-linearity and heteroscedasticity). Top-right: Q-Q plot
(check for normality of residuals). Bottom-left: scale-location (check
for homoscedasticity). Bottom-right: residuals vs. leverage (identify
influential cases with high Cook’s distance).
</p>
</div>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<pre class="r"><code># Cook&#39;s D &gt; 4/n is a widely used cutoff (Bollen &amp; Jackman, 1990 - but cited
# only as a heuristic here, not a strict rule). It flags observations whose
# leverage * residual product is large enough to materially shift the fitted
# coefficients. With n = 24 the threshold is generous (~0.17), so a flagged
# case warrants inspection rather than automatic removal.
cooks_d &lt;- cooks.distance(model_full)
threshold &lt;- 4 / nrow(reg_data)
influential &lt;- which(cooks_d &gt; threshold)

if (length(influential) &gt; 0) {
  cat(sprintf(&quot;Influential cases (Cook&#39;s D &gt; %.3f):\n&quot;, threshold))
  cat(&quot;  Row indices:&quot;, paste(influential, collapse = &quot;, &quot;), &quot;\n&quot;)
  cat(&quot;  Subject numbers:&quot;, paste(reg_data$subjnum[influential], collapse = &quot;, &quot;), &quot;\n&quot;)
  cat(&quot;  Cook&#39;s D values:&quot;, paste(round(cooks_d[influential], 3), collapse = &quot;, &quot;), &quot;\n&quot;)
} else {
  cat(&quot;No influential cases detected.\n&quot;)
}</code></pre>
<pre><code>## Influential cases (Cook&#39;s D &gt; 0.235):
##   Row indices: 5, 9 
##   Subject numbers: 9, 23 
##   Cook&#39;s D values: 0.477, 0.72</code></pre>
</div>
<div id="standardized-coefficients" class="section level2">
<h2>Standardized Coefficients</h2>
<pre class="r"><code># Standardize all variables (X and Y) for comparable effect sizes; the
# resulting lm coefficients are standardized betas. We wrap scale() in
# as.numeric() because scale() returns a 1-column matrix with attributes,
# which dplyr would store as a matrix column - fine for lm() in most cases
# but fragile for downstream broom::tidy() across versions.
reg_data_z &lt;- reg_data %&gt;%
  mutate(across(c(Blink_CD, all_of(predictors)), ~ as.numeric(scale(.))))

model_std &lt;- lm(Blink_CD ~ learning_slope + transition_trial +
                  end_p_efficient + overall_suppress + suppress_growth,
                data = reg_data_z)

# Extract standardized coefficients
std_coefs &lt;- broom::tidy(model_std) %&gt;%
  filter(term != &quot;(Intercept)&quot;) %&gt;%
  mutate(term = unname(predictor_labels[term]))

kable(std_coefs, digits = c(0, 3, 3, 2, 4),
      caption = &quot;Table 5. Standardized regression coefficients predicting Blink_CD from HMM features.&quot;,
      col.names = c(&quot;Predictor&quot;, &quot;β&quot;, &quot;SE&quot;, &quot;t&quot;, &quot;p&quot;))</code></pre>
<table>
<caption>Table 5. Standardized regression coefficients predicting
Blink_CD from HMM features.</caption>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="right">β</th>
<th align="right">SE</th>
<th align="right">t</th>
<th align="right">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Learning Slope</td>
<td align="right">-0.225</td>
<td align="right">0.371</td>
<td align="right">-0.61</td>
<td align="right">0.5571</td>
</tr>
<tr class="even">
<td align="left">Transition Trial</td>
<td align="right">0.059</td>
<td align="right">0.366</td>
<td align="right">0.16</td>
<td align="right">0.8752</td>
</tr>
<tr class="odd">
<td align="left">End-State P(Efficient)</td>
<td align="right">-0.218</td>
<td align="right">0.357</td>
<td align="right">-0.61</td>
<td align="right">0.5537</td>
</tr>
<tr class="even">
<td align="left">Overall Suppression</td>
<td align="right">0.183</td>
<td align="right">0.338</td>
<td align="right">0.54</td>
<td align="right">0.5998</td>
</tr>
<tr class="odd">
<td align="left">Suppression Growth</td>
<td align="right">-0.079</td>
<td align="right">0.440</td>
<td align="right">-0.18</td>
<td align="right">0.8603</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Reorder the predictor factor by |β| so the largest-magnitude coefficient
# sits at the top of the y-axis and the weakest at the bottom - this puts
# the most informative predictors visually first regardless of sign.
std_coefs_ci &lt;- broom::tidy(model_std, conf.int = TRUE) %&gt;%
  filter(term != &quot;(Intercept)&quot;) %&gt;%
  mutate(term = unname(predictor_labels[term]),
         term = fct_reorder(term, abs(estimate)))

ggplot(std_coefs_ci, aes(x = estimate, y = term)) +
  geom_vline(xintercept = 0, linetype = &quot;dashed&quot;, color = &quot;gray50&quot;) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                 height = 0.2, linewidth = 0.8) +
  geom_point(size = 3, color = col_efficient) +
  labs(x = &quot;Standardized Coefficient (β)&quot;,
       y = NULL) +
  manuscript_theme</code></pre>
<pre><code>## Warning: `geom_errobarh()` was deprecated in ggplot2 4.0.0.
## ℹ Please use the `orientation` argument of `geom_errorbar()` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## `height` was translated to `width`.</code></pre>
<div class="figure">
<img src="p12_files/figure-html/coefficient-plot-1.png" alt="Figure 5. Standardized regression coefficients (β) with 95% confidence intervals. Bars crossing zero indicate non-significant predictors at α = .05." width="768" />
<p class="caption">
Figure 5. Standardized regression coefficients (β) with 95% confidence
intervals. Bars crossing zero indicate non-significant predictors at α =
.05.
</p>
</div>
</div>
</div>
<div id="exploratory-alternative-rsvp-outcomes" class="section level1">
<h1>Exploratory: Alternative RSVP Outcomes</h1>
<p>As an exploratory extension, we examine whether HMM features also
predict the attentional blink for other distractor conditions (Blink_ND,
Blink_VD_Match, Blink_VD_Mismatch). If the HMM-captured suppression is
specific to the consistent distractor color, we would expect stronger
prediction of Blink_CD than of other blink measures.</p>
<pre class="r"><code># Same map_dfr pattern as the primary bivariate-correlations chunk, but inverted: instead of iterating over predictors with one outcome (Blink_CD), we iterate over outcomes with one predictor (the strongest from the primary analysis). 
# The expected pattern under CD-specific transfer is that the correlation magnitude is largest for Blink_CD and smaller for the other blink measures, where there was no opportunity for VST learning to help.
outcomes &lt;- c(&quot;Blink_CD&quot;, &quot;Blink_ND&quot;, &quot;Blink_VD_Match&quot;, &quot;Blink_VD_Mismatch&quot;)
outcome_labels &lt;- c(
  Blink_CD = &quot;Consistent Distractor&quot;,
  Blink_ND = &quot;No Distractor&quot;,
  Blink_VD_Match = &quot;Variable (Match)&quot;,
  Blink_VD_Mismatch = &quot;Variable (Mismatch)&quot;
)

best_pred &lt;- strongest$variable

exploratory_cors &lt;- map_dfr(outcomes, function(outcome) {
  d &lt;- transfer_data %&gt;%
    select(all_of(outcome), all_of(best_pred)) %&gt;%
    drop_na()

  ct &lt;- cor.test(d[[best_pred]], d[[outcome]])

  tibble(
    Outcome = outcome_labels[outcome],
    Predictor = predictor_labels[best_pred],
    r = ct$estimate,
    p = ct$p.value,
    n = nrow(d)
  )
})

kable(exploratory_cors, digits = c(0, 0, 3, 4, 0),
      caption = sprintf(&quot;Table 6. Correlation between %s and each RSVP blink measure.&quot;,
                        predictor_labels[best_pred]))</code></pre>
<table>
<caption>Table 6. Correlation between End-State P(Efficient) and each
RSVP blink measure.</caption>
<thead>
<tr class="header">
<th align="left">Outcome</th>
<th align="left">Predictor</th>
<th align="right">r</th>
<th align="right">p</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Consistent Distractor</td>
<td align="left">End-State P(Efficient)</td>
<td align="right">-0.363</td>
<td align="right">0.0815</td>
<td align="right">24</td>
</tr>
<tr class="even">
<td align="left">No Distractor</td>
<td align="left">End-State P(Efficient)</td>
<td align="right">0.007</td>
<td align="right">0.9756</td>
<td align="right">24</td>
</tr>
<tr class="odd">
<td align="left">Variable (Match)</td>
<td align="left">End-State P(Efficient)</td>
<td align="right">-0.091</td>
<td align="right">0.6724</td>
<td align="right">24</td>
</tr>
<tr class="even">
<td align="left">Variable (Mismatch)</td>
<td align="left">End-State P(Efficient)</td>
<td align="right">-0.212</td>
<td align="right">0.3204</td>
<td align="right">24</td>
</tr>
</tbody>
</table>
</div>
<div id="specificity-analysis-blink-cost-cd---vd_mismatch"
class="section level1">
<h1>Specificity Analysis: Blink Cost (CD - VD_Mismatch)</h1>
<p>The primary analysis above tested whether HMM features predict the
absolute attentional blink for the consistent distractor color
(Blink_CD). However, Blink_CD confounds the trained-distractor effect
with general attentional ability. To quantify the transfer signal
relative to a baseline distractor that participants had no opportunity
to learn about, we compute a blink cost score: Blink_Cost = Blink_CD -
Blink_VD_Mismatch. A negative cost indicates that the consistent
distractor color produces <em>less</em> attentional blink than a
variable-location distractor with a non-matching colour - consistent
with learned suppression transferring to the RSVP task and reducing the
attentional cost of the trained colour.</p>
<p>If HMM features predict Blink_CD but not Blink_Cost, the apparent
association reflects general attentional efficiency that lifts target
accuracy across all conditions. If they predict Blink_Cost, that
provides stronger evidence for transfer specific to the trained colour
relative to an untrained-colour baseline.</p>
<pre class="r"><code># Compute blink cost: CD - VD_Mismatch (untrained-colour baseline).
# Negative = less blink for the trained CD colour than for an unmatched variable distractor - the expected direction if learned suppression transfers.
transfer_data &lt;- transfer_data %&gt;%
  mutate(Blink_Cost = Blink_CD - Blink_VD_Mismatch)

# One-sample t-test: is blink cost different from zero?
t.test(transfer_data$Blink_Cost)</code></pre>
<pre><code>## 
##  One Sample t-test
## 
## data:  transfer_data$Blink_Cost
## t = 0.12089, df = 23, p-value = 0.9048
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.04771035  0.05363270
## sample estimates:
##   mean of x 
## 0.002961175</code></pre>
<pre class="r"><code>ggplot(transfer_data, aes(x = Blink_Cost)) +
  geom_histogram(fill = col_engaged, alpha = 0.7, bins = 12,
                 color = &quot;white&quot;, linewidth = 0.5) +
  geom_vline(xintercept = 0, linetype = &quot;dashed&quot;, color = &quot;gray30&quot;, linewidth = 0.8) +
  geom_vline(xintercept = mean(transfer_data$Blink_Cost, na.rm = TRUE),
             color = col_efficient, linewidth = 1.2) +
  labs(x = &quot;Blink Cost (CD - VD_Mismatch)&quot;,
       y = &quot;Count&quot;) +
  manuscript_theme</code></pre>
<div class="figure">
<img src="p12_files/figure-html/blink-cost-distribution-1.png" alt="Figure 6. Distribution of blink cost scores (Blink_CD - Blink_VD_Mismatch). Negative values indicate that the consistent distractor colour produces less attentional blink than an unmatched-colour variable distractor - consistent with suppression transfer to the trained colour." width="576" />
<p class="caption">
Figure 6. Distribution of blink cost scores (Blink_CD -
Blink_VD_Mismatch). Negative values indicate that the consistent
distractor colour produces less attentional blink than an
unmatched-colour variable distractor - consistent with suppression
transfer to the trained colour.
</p>
</div>
<div id="bivariate-correlations-hmm-features-blink-cost"
class="section level2">
<h2>Bivariate Correlations: HMM Features × Blink Cost</h2>
<pre class="r"><code># Run bivariate correlations with Blink_Cost
cost_cors &lt;- map_dfr(predictors, function(pred) {
  d &lt;- transfer_data %&gt;%
    select(all_of(pred), Blink_Cost) %&gt;%
    drop_na()

  ct &lt;- cor.test(d[[pred]], d$Blink_Cost)

  tibble(
    Predictor = predictor_labels[pred],
    n = nrow(d),
    r = ct$estimate,
    t = ct$statistic,
    df = ct$parameter,
    p = ct$p.value,
    CI_lower = ct$conf.int[1],
    CI_upper = ct$conf.int[2]
  )
})

kable(cost_cors, digits = c(0, 0, 3, 2, 0, 4, 3, 3),
      caption = &quot;Table 7. Bivariate correlations between HMM features and Blink Cost (CD - VD_Mismatch).&quot;)</code></pre>
<table>
<caption>Table 7. Bivariate correlations between HMM features and Blink
Cost (CD - VD_Mismatch).</caption>
<colgroup>
<col width="34%" />
<col width="4%" />
<col width="10%" />
<col width="8%" />
<col width="4%" />
<col width="10%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Predictor</th>
<th align="right">n</th>
<th align="right">r</th>
<th align="right">t</th>
<th align="right">df</th>
<th align="right">p</th>
<th align="right">CI_lower</th>
<th align="right">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Learning Slope</td>
<td align="right">24</td>
<td align="right">-0.144</td>
<td align="right">-0.68</td>
<td align="right">22</td>
<td align="right">0.5020</td>
<td align="right">-0.517</td>
<td align="right">0.275</td>
</tr>
<tr class="even">
<td align="left">Transition Trial</td>
<td align="right">17</td>
<td align="right">0.001</td>
<td align="right">0.01</td>
<td align="right">15</td>
<td align="right">0.9960</td>
<td align="right">-0.480</td>
<td align="right">0.482</td>
</tr>
<tr class="odd">
<td align="left">End-State P(Efficient)</td>
<td align="right">24</td>
<td align="right">-0.088</td>
<td align="right">-0.41</td>
<td align="right">22</td>
<td align="right">0.6837</td>
<td align="right">-0.474</td>
<td align="right">0.327</td>
</tr>
<tr class="even">
<td align="left">Overall Suppression</td>
<td align="right">24</td>
<td align="right">0.460</td>
<td align="right">2.43</td>
<td align="right">22</td>
<td align="right">0.0237</td>
<td align="right">0.070</td>
<td align="right">0.728</td>
</tr>
<tr class="odd">
<td align="left">Suppression Growth</td>
<td align="right">24</td>
<td align="right">-0.020</td>
<td align="right">-0.09</td>
<td align="right">22</td>
<td align="right">0.9254</td>
<td align="right">-0.420</td>
<td align="right">0.386</td>
</tr>
</tbody>
</table>
<pre class="r"><code>plot_data_cost &lt;- transfer_data %&gt;%
  select(all_of(predictors), Blink_Cost) %&gt;%
  pivot_longer(cols = all_of(predictors), names_to = &quot;feature&quot;, values_to = &quot;value&quot;) %&gt;%
  mutate(feature = unname(predictor_labels[feature]),
         feature = factor(feature, levels = unname(predictor_labels)))

ggplot(plot_data_cost, aes(x = value, y = Blink_Cost)) +
  geom_point(size = 2.5, color = &quot;gray35&quot;, alpha = 0.8) +
  geom_smooth(method = &quot;lm&quot;, se = TRUE, color = col_efficient, fill = col_efficient, alpha = 0.2) +
  facet_wrap(~ feature, scales = &quot;free_x&quot;, ncol = 3) +
  labs(x = &quot;Feature Value&quot;, y = &quot;Blink Cost (CD - VD_Mismatch)&quot;) +
  manuscript_theme +
  theme(strip.text = element_text(size = 11))</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 7 rows containing non-finite outside the scale range
## (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 7 rows containing missing values or values outside the scale range
## (`geom_point()`).</code></pre>
<div class="figure">
<img src="p12_files/figure-html/blink-cost-scatterplots-1.png" alt="Figure 7. Scatterplots of each HMM feature against Blink Cost. Blue lines show least-squares fit with 95% CI." width="960" />
<p class="caption">
Figure 7. Scatterplots of each HMM feature against Blink Cost. Blue
lines show least-squares fit with 95% CI.
</p>
</div>
</div>
<div id="multiple-regression-hmm-features-predicting-blink-cost"
class="section level2">
<h2>Multiple Regression: HMM Features Predicting Blink Cost</h2>
<pre class="r"><code># Fit the full model
cost_reg_data &lt;- transfer_data %&gt;%
  select(subjnum, Blink_Cost, all_of(predictors)) %&gt;%
  drop_na()

model_cost &lt;- lm(Blink_Cost ~ learning_slope + transition_trial +
                   end_p_efficient + overall_suppress + suppress_growth,
                 data = cost_reg_data)

summary(model_cost)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Blink_Cost ~ learning_slope + transition_trial + 
##     end_p_efficient + overall_suppress + suppress_growth, data = cost_reg_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.14398 -0.10583  0.01811  0.08818  0.13206 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)       5.993e-02  2.144e-01   0.280   0.7850  
## learning_slope   -1.907e+02  1.792e+02  -1.064   0.3101  
## transition_trial -2.367e-04  4.719e-04  -0.502   0.6258  
## end_p_efficient  -8.629e-02  6.537e-01  -0.132   0.8974  
## overall_suppress  3.647e+00  1.353e+00   2.696   0.0208 *
## suppress_growth  -7.209e-01  7.869e-01  -0.916   0.3793  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1191 on 11 degrees of freedom
## Multiple R-squared:  0.4154, Adjusted R-squared:  0.1497 
## F-statistic: 1.563 on 5 and 11 DF,  p-value: 0.2491</code></pre>
<pre class="r"><code># Extract key statistics
cost_r2 &lt;- summary(model_cost)$r.squared
cost_adj_r2 &lt;- summary(model_cost)$adj.r.squared
cost_f &lt;- summary(model_cost)$fstatistic
cost_f_p &lt;- pf(cost_f[1], cost_f[2], cost_f[3], lower.tail = FALSE)

cat(sprintf(&quot;\nBlink Cost model: R² = %.3f, adj R² = %.3f, F(%d, %d) = %.2f, p = %.4f\n&quot;,
            cost_r2, cost_adj_r2, cost_f[2], cost_f[3], cost_f[1], cost_f_p))</code></pre>
<pre><code>## 
## Blink Cost model: R² = 0.415, adj R² = 0.150, F(5, 11) = 1.56, p = 0.2491</code></pre>
<pre class="r"><code># Pre-compute Blink_CD model stats for inline text below
r2 &lt;- summary(model_full)$r.squared
adj_r2 &lt;- summary(model_full)$adj.r.squared
f_stat &lt;- summary(model_full)$fstatistic
f_p &lt;- pf(f_stat[1], f_stat[2], f_stat[3], lower.tail = FALSE)</code></pre>
<pre class="r"><code># Side-by-side comparison of effect sizes for each predictor against the two outcomes: raw Blink_CD vs. Blink Cost (CD - VD_Mismatch). Same point styling encodes significance (filled triangle = p &lt; .05, filled circle = p &lt; .10, open circle = n.s.); position_dodge separates the two outcomes per predictor.
comparison &lt;- bind_rows(
  cor_results %&gt;%
    select(Predictor, r, p) %&gt;%
    mutate(Outcome = &quot;Blink_CD&quot;),
  cost_cors %&gt;%
    select(Predictor, r, p) %&gt;%
    mutate(Outcome = &quot;Blink Cost\n(CD - VD_Mismatch)&quot;)
) %&gt;%
  mutate(sig = case_when(p &lt; .05 ~ &quot;p &lt; .05&quot;, p &lt; .10 ~ &quot;p &lt; .10&quot;, TRUE ~ &quot;n.s.&quot;),
         Predictor = factor(Predictor, levels = rev(unname(predictor_labels))))

ggplot(comparison, aes(x = r, y = Predictor, color = Outcome, shape = sig)) +
  geom_vline(xintercept = 0, linetype = &quot;dashed&quot;, color = &quot;gray50&quot;) +
  geom_point(size = 3.5, position = position_dodge(width = 0.5)) +
  scale_color_manual(values = c(&quot;Blink_CD&quot; = col_efficient,
                                &quot;Blink Cost\n(CD - VD_Mismatch)&quot; = col_engaged)) +
  scale_shape_manual(values = c(&quot;p &lt; .05&quot; = 17, &quot;p &lt; .10&quot; = 16, &quot;n.s.&quot; = 1)) +
  labs(x = &quot;Pearson r&quot;, y = NULL, color = &quot;Outcome&quot;, shape = &quot;Significance&quot;) +
  manuscript_theme +
  theme(legend.position = &quot;bottom&quot;)</code></pre>
<div class="figure">
<img src="p12_files/figure-html/blink-cost-comparison-1.png" alt="Figure 8. Comparison of bivariate correlations: HMM features predicting Blink_CD (general blink) vs. Blink Cost (CD - VD_Mismatch, transfer-specific). Larger absolute correlations with Blink_CD than Blink Cost would suggest general attentional efficiency drives the association rather than transfer to the trained colour." width="864" />
<p class="caption">
Figure 8. Comparison of bivariate correlations: HMM features predicting
Blink_CD (general blink) vs. Blink Cost (CD - VD_Mismatch,
transfer-specific). Larger absolute correlations with Blink_CD than
Blink Cost would suggest general attentional efficiency drives the
association rather than transfer to the trained colour.
</p>
</div>
<p>Neither the Blink_CD model (R² = 0.146, p = 0.8543) nor the Blink
Cost model (R² = 0.415, p = 0.2491) reached significance. The pattern of
bivariate correlations can clarify whether the trend-level effects
observed for Blink_CD reflect general efficiency or transfer to the
trained colour.</p>
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>The multiple regression testing whether HMM-derived features from the
VST predict attentional blink magnitude for the consistent distractor
color (Blink_CD) in the RSVP task yielded R² = 0.146 (adjusted R² =
-0.242), F(5, 11) = 0.38, p = 0.8543.</p>
<p>The overall model did not reach significance, suggesting that the
HMM-derived suppression learning features did not reliably predict
attentional blink magnitude for the consistent distractor color in this
sample. This null result may reflect several factors: the modest sample
size (n = 24) limits power to detect moderate effects; the RSVP blink
measure may capture processes partially distinct from the spatial
suppression indexed by the HMM; or transfer of learned suppression may
operate through mechanisms not fully captured by the five features
extracted here. Nonetheless, the direction and magnitude of individual
predictor effects remain informative for guiding future work with larger
samples.</p>
<p>At the bivariate level, no individual predictor reached significance
at p &lt; .05. 2 predictor(s) showed trends (p &lt; .10): Learning
Slope, End-State P(Efficient). The strongest zero-order relationship was
with End-State P(Efficient) (r = -0.363, p = 0.0815).</p>
<div id="specificity-blink-cost-cd---vd_mismatch"
class="section level2">
<h2>Specificity: Blink Cost (CD - VD_Mismatch)</h2>
<p>To test whether the HMM features predict transfer to the trained
distractor colour rather than general attentional efficiency, we
computed a blink cost score (Blink_CD - Blink_VD_Mismatch) that
benchmarks the trained-colour blink against a variable distractor with a
non-matching colour - a baseline that participants had no opportunity to
learn about. The Blink Cost regression was not significant (R² = 0.415,
p = 0.2491). Neither the raw Blink_CD model nor the Blink Cost model
reached significance, consistent with the overall null transfer
finding.</p>
<p>The comparison of bivariate correlation patterns across the two
outcomes (Figure 8) provides the clearest diagnostic: if correlations
weaken when moving from Blink_CD to Blink Cost, the original
associations were partially driven by general capacity differences
rather than suppression-specific transfer. This distinction is important
for interpreting the theoretical significance of any HMM-RSVP
relationship.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
